### PR TITLE
Added javascript file to convert octal to hexadecimal.

### LINKED ISSUE #456: Convert octal to hexadecimal
### Description

Write a program to convert octal to hexadecimal

Octal is a base-8 number system. It uses only eight digits: 0, 1, 2, 3, 4, 5, 6, and 7. The digits are called octits. An octit is the smallest unit of information in a computer. An octit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, or 7, or it can be used to represent a single state, such as on or off.

Hexadecimal is a base-16 number system. It uses sixteen digits: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, and F. The digits are called hexits. A hexit is the smallest unit of information in a computer. A hexit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, or F, or it can be used to represent a single state, such as on or off.

To convert an octal number to hexadecimal, we can use the following algorithm:

1. Convert the octal number to decimal.
2. Convert the decimal number to hexadecimal.

```
Input  : 12
Output : A
```

### Tracking Issues

- [ ] Write a C program to convert octal to hexadecimal
- [ ] Write a C# program to convert octal to hexadecimal
- [ ] Write a C++ program to convert octal to hexadecimal
- [ ] Write a Dart program to convert octal to hexadecimal
- [ ] Write a F# program to convert octal to hexadecimal
- [ ] Write a GO program to convert octal to hexadecimal
- [ ] Write a Java program to convert octal to hexadecimal
- [ ] Write a JavaScript program to convert octal to hexadecimal
- [ ] Write a Julia program to convert octal to hexadecimal
- [ ] Write a Kotlin program to convert octal to hexadecimal
- [ ] Write a Perl program to convert octal to hexadecimal
- [ ] Write a PHP program to convert octal to hexadecimal
- [ ] Write a Python program to convert octal to hexadecimal
- [ ] Write a R program to convert octal to hexadecimal
- [ ] Write a Ruby program to convert octal to hexadecimal
- [ ] Write a Rust program to convert octal to hexadecimal
- [ ] Write a Scala program to convert octal to hexadecimal
- [ ] Write a Swift program to convert octal to hexadecimal
- [ ] Write a TypeScript program to convert octal to hexadecimal

### LINKED ISSUE #464: Write a JavaScript program to convert octal to hexadecimal
### Description

Write a JavaScript program to convert octal to hexadecimal

Octal is a base-8 number system. It uses only eight digits: 0, 1, 2, 3, 4, 5, 6, and 7. The digits are called octits. An octit is the smallest unit of information in a computer. An octit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, or 7, or it can be used to represent a single state, such as on or off.

Hexadecimal is a base-16 number system. It uses sixteen digits: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, and F. The digits are called hexits. A hexit is the smallest unit of information in a computer. A hexit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, or F, or it can be used to represent a single state, such as on or off.

To convert an octal number to hexadecimal, we can use the following algorithm:

1. Convert the octal number to decimal.
2. Convert the decimal number to hexadecimal.

```
Input  : 12
Output : A
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertOctalToHexadecimal.js` file
- Add `ConvertOctalToHexadecimal.js` file in `convert-octal-to-hexadecimal` folder

</details>

### PR DESCRIPTION
**Pull request by DiamonndAde**
### Why:

Closes codinasion/codinasion#386 

### What's being changed:
I wrote javascript code to convert octal to hexadecimal

### CODE REVIEW

**Comment by victoriacheng15** [comment]
Hey @DiamonndAde,

The issue should be codinasion/codinasion#386 instead. 

Thank you!

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Hey @DiamonndAde 

Please update filename to `ConvertOctalToHexadecimal.js`

Please comment `!assign` on linked issue #464 (to prevent any conflict)

```
!assign
```

**Review by victoriacheng15 — APPROVED** [review]
Please update the file name based on the naming convention as the above mentioned. Otherwise, it looks good.

Thank you for contributing! 👍

**Review by victoriacheng15 — APPROVED** [review]
Thank you for contributing! 👍

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
