### PR TITLE
volume of cube

### LINKED ISSUE #50: Write a C++ program to find volume of cube
### Description

Write a C++ program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.cpp` file
- Add `FindVolumeOfCube.cpp` file in `find-volume-of-cube` folder

</details>

### LINKED ISSUE #66: Write a C++ program to find volume of cube
### Description

Write a C++ program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.cpp` file
- Add `FindVolumeOfCube.cpp` file in `find-volume-of-cube` folder

</details>

### PR DESCRIPTION
**Pull request by SidharthSarangi**
### Why:

fixes codinasion/codinasion#50 

### What's being changed:
Added the c++ program to find the volume of a cube.

### CODE REVIEW

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Can you change file names to `FindVolumeOfCube.cpp` based on the naming convention under `how to contribute` from #66? Otherwise, it looks good!

Thank you for contributing!

**Review by victoriacheng15 — APPROVED** [review]
Awesome! 👍

**Comment by SidharthSarangi** [comment]
@harshraj8843 @PrajwalBorkar   please check.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
