### PR TITLE
Convert Hours to seconds using JS

### LINKED ISSUE #1160: Write a JavaScript program to convert hours to seconds
### Description

Write a JavaScript program to convert hours to seconds

1 hour = 60 minutes = 3600 seconds

```
Input  : 5
Output : 18000
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertHoursToSeconds.js` file
- Add `ConvertHoursToSeconds.js` file in `convert-hours-to-seconds` folder

</details>

### PR DESCRIPTION
**Pull request by greeshma-d**
Closes codinasion/codinasion#927 

### What's being changed:

Added JS file to convert hours to seconds in JS

### CODE REVIEW

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Please update folder name

**Comment by harshraj8843** [comment]
Hey @Greeshma-frontier 

Please update the folder name

**Comment by Greeshma-frontier** [comment]
> Hey @Greeshma-frontier
> 
> Please update the folder name

@harshraj8843 updated folder

**Review by harshraj8843 — APPROVED** [review]
Nice 🤩 

Thanks for contributing 👍🏻

**Pull request merged**
