### PR TITLE
Create SecondLargestNumberInArray.go

### LINKED ISSUE #3563: Write a GO program to find second largest number in an array
### Description

Write a GO program to find second largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find_second_largest_number_in_an_array.go` file
- Add `find_second_largest_number_in_an_array.go` file in `find-second-largest-number-in-an-array` folder

</details>

### PR DESCRIPTION
**Pull request by HeYPoonam**
### Why:

Closes codinasion/codinasion#2619

### CODE REVIEW

**Comment by HeYPoonam** [comment]
@harshraj8843 please review my code

**Review by victoriacheng15 — COMMENTED** [review]
What if the array has 10 elements?

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Comment by harshraj8843** [comment]
> What if the array has 10 elements?

code can be improved further

**Pull request merged**
