### PR TITLE
Solution of sum of digits of a number by recursion

### LINKED ISSUE #740: Write a Java program to find sum of digits of a number by recursion
### Description

Write a Java program to find sum of digits of a number by recursion

Suppose we have a number `n` and we want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

Recursion is a method of solving a problem where the solution depends on solutions to smaller instances of the same problem. In this case, we can use recursion to find the sum of digits of a number.

```
Input  : 123
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfDigitsOfANumberByRecursion.java` file
- Add `FindSumOfDigitsOfANumberByRecursion.java` file in `find-sum-of-digits-of-a-number-by-recursion` folder

</details>

### PR DESCRIPTION
**Pull request by Harsh3341**
### Why:

Closes codinasion/codinasion#606

### What's being changed:

Created Solution for sum of digits of a number by recursion using java

### CODE REVIEW

**Review by victoriacheng15 — COMMENTED** [review]
I got this error after ran the code.

image

**Comment by Harsh3341** [comment]
> I got this error after ran the code.
> 
> image

Just change the class name to Main as your file name is Main.java, in the issue, it's told to create file name as FindSumOfDigitsOfANumberByRecursion.java so I created the class as FindSumOfDigitsOfANumberByRecursion

**Comment by victoriacheng15** [comment]
> > I got this error after ran the code.
> > image
> 
> Just change the class name to Main as your file name is Main.java, in the issue, it's told to create file name as FindSumOfDigitsOfANumberByRecursion.java so I created the class as FindSumOfDigitsOfANumberByRecursion
> 
> Main java - Test - Visual Studio Code 03-10-2022 09_56_47

I didn't know about the file and function names need to be the same. I will keep this in mind for the future. Thank you for letting me know!

**Review by victoriacheng15 — APPROVED** [review]
Looks good! 

Thank you for contributing! 👍 

Happy October!

**Pull request merged**
