### PR TITLE
Write a Go program to convert hexadecimal to octal

### LINKED ISSUE #1438: Write a GO program to convert hexadecimal to octal
### Description

Write a GO program to convert hexadecimal to octal

Hexadecimal is a base-16 number system. It uses sixteen digits: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, and F. The digits are called hexits. A hexit is the smallest unit of information in a computer. A hexit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, or F, or it can be used to represent a single state, such as on or off.

Octal is a base-8 number system. It uses only eight digits: 0, 1, 2, 3, 4, 5, 6, and 7. The digits are called octits. An octit is the smallest unit of information in a computer. An octit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, or 7, or it can be used to represent a single state, such as on or off.

To convert a hexadecimal number to octal, we can use the following algorithm:

1. Convert the hexadecimal number to decimal.
2. Convert the decimal number to octal.

```
Input  : A
Output : 12
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_hexadecimal_to_octal.go` file
- Add `convert_hexadecimal_to_octal.go` file in `convert-hexadecimal-to-octal` folder

</details>

### PR DESCRIPTION
**Pull request by amoghrajesh**
### Why:

Closes codinasion/codinasion#1129 

### What's being changed:
- Go file added to convert a hexadecimal to octal
- Run by running the following command, go version >= 1.16
```
cd program
go run convert-hexadecimal-to-octal/convert-hexadecimal-to-octal.go
```
- Enter the input and get the output
Example:
```
➜  program git:(convert-hexadecimal-to-octal) ✗ go run convert-hexadecimal-to-octal/convert-hexadecimal-to-octal.go
beef
the octal for hex: beef is oct: 137357 
➜  program git:(convert-hexadecimal-to-octal) ✗ go run convert-hexadecimal-to-octal/convert-hexadecimal-to-octal.go
A
the octal for hex: A is oct: 12 
```

### CODE REVIEW

**Comment by amoghrajesh** [comment]
@PrajwalBorkar @victoriacheng15 can you help with a review?

**Comment by amoghrajesh** [comment]
@PrajwalBorkar @victoriacheng15 @harshraj8843 can you help in reviews?

**Comment by victoriacheng15** [comment]
Please avoid ping us for review. We will review when we are able to do so.

Thank you!

**Review by victoriacheng15 — APPROVED** [review]
Looks good.

Thank you for contributing!

**Pull request merged**
