### PR TITLE
Resolves #3360

### LINKED ISSUE #3360: Write a Python program to check leap year
### Description

Write a Python program to check leap year

Leap years are years that are divisible by 4, but not by 100, unless they are also divisible by 400. For example, 1996 is a leap year, but 1900 is not. Write a function that takes a year as a parameter and returns True if the year is a leap year, False otherwise.

```
Input  : 2016
Output : Leap Year
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/check-leap-year.py` file
- Add `check-leap-year.py` file in `check-leap-year` folder

</details>

### PR DESCRIPTION
**Pull request by kituuu**
### Why:

Closes codinasion/codinasion#2480

### CODE REVIEW

**Comment by kituuu** [comment]
Please give Hacktoberfest tag :))

**Comment by Tc2r1** [comment]
@kituuu this repo is excluded from hacktoberfest2022, however I have a repo that is not excluded you may be able to contribute to:

shameless self plug: lol its not as fancy as this one but its honestly to help newer developers, lmk:

https://github.com/Tc2r1/DevInterview_Questions

**Comment by kituuu** [comment]
Okie

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
