### PR TITLE
Create FindSumOfSquaresOfNumbers.ts

### LINKED ISSUE #5250: Find sum of squares of numbers
### Description

Write a program to find sum of squares of numbers

Suppose you have a list of numbers, and you want to find the sum of the squares of those numbers. For example, if you have the list `[1, 2, 3]`, you want to find the sum of the squares of those numbers, which is `1^2 + 2^2 + 3^2 = 14`.

```
Input  : 1 2 3 4 5
Output : 55
```

### Tracking Issues

- [ ] #5251
- [ ] #5252
- [ ] #5253
- [ ] #5254
- [ ] #5255
- [ ] #5256
- [ ] #5257
- [ ] #5258
- [ ] #5259
- [ ] #5260
- [ ] #5261
- [ ] #5262
- [ ] #5263
- [ ] #5264
- [ ] #5265
- [ ] #5266
- [ ] #5267
- [ ] #5268
- [ ] #5269
- [ ] #5270

### PR DESCRIPTION
**Pull request by xxdydx**
### Why:
Closes codinasion/codinasion#3924 

edited: linked to the correct issue

### What's being changed:
Added script that finds out the sum of squares of numbers

### CODE REVIEW

**Review by anandfresh — COMMENTED** [review]
You should get assign to the the issue first

**Review by anandfresh — APPROVED** [review]

**Comment by victoriacheng15** [comment]
@anandfresh please double-check the linked issue. The linked issue is not the correct one, and they were not assigned yet.

**Comment by anandfresh** [comment]
> codinasion/codinasion#3924

@victoriacheng15  The linked issue is the correct one only . 
For assigning the issue , already i have given a comment asking him to assign it by himself .
For few who are not aware of this process , We may need to help in assigning as well for the first time .

**Comment by victoriacheng15** [comment]
> > codinasion/codinasion#3924
> 
> @victoriacheng15 The linked issue is the correct one only . For assigning the issue , already i have given a comment asking him to assign it by himself . For few who are not aware of this process , We may need to help in assigning as well for the first time .

It is because I changed it. You can see the first post was edited by me first. 

image

**Pull request merged**
