### PR TITLE
Write a Python program to convert string to consonantcase #5156

### LINKED ISSUE #5156: Write a Python program to convert string to consonantcase
### Description

Write a Python program to convert string to consonantcase

Consonantcase is a style of writing in which all consonants are converted to uppercase and all vowels are converted to lowercase.

```
Input  : "hello world"
Output : "HeLLo WoRLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-string-to-consonantcase.py` file
- Add `convert-string-to-consonantcase.py` file in `program/convert-string-to-consonantcase` folder

</details>

### PR DESCRIPTION
**Pull request by mrsaxman29**
### Why:

Closes codinasion/codinasion#3813

### What's being changed:

Write a Python program to convert string to consonantcase codinasion/codinasion#3813

### CODE REVIEW

**Comment by mrsaxman29** [comment]
I'm new and this is my first contribution to any open source project - please lmk what I messed up.  Thank you reviewers!

**Comment by harshraj8843** [comment]
Hey @mrsaxman29 

Please comment `!assign` on codinasion/codinasion#3813 to be auto-assigned for the issue, to prevent any conflict 👍🏻

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Review by anandfresh — CHANGES_REQUESTED** [review]
@mrsaxman29  Please assign this issue (#5156) to your name

**Review by hi-Kartik2004 — COMMENTED** [review]
Hi @mrsaxman29, Thanks for your interest to contribute, Can you take user input of the string which will undergo the operation, instead of a hard-coded value?

**Review by hi-Kartik2004 — APPROVED** [review]

**Comment by hi-Kartik2004** [comment]
Hi @mrsaxman29, I have **added user input** instead of the hard-coded string "hello world"

**Review by anandfresh — CHANGES_REQUESTED** [review]
@mrsaxman29  , Please assign the issue (https://github.com/codinasion/program/issues/5156)  to your name before raising a PR

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
