### PR TITLE
C# program to divide two numbers 

### LINKED ISSUE #90: Write a C# program to divide two numbers
### Description

Write a C# program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.cs` file
- Add `DivideTwoNumbers.cs` file in `divide-two-numbers` folder

</details>

### LINKED ISSUE #107: Write a C# program to divide two numbers
### Description

Write a C# program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.cs` file
- Add `DivideTwoNumbers.cs` file in `divide-two-numbers` folder

</details>

### PR DESCRIPTION
**Pull request by Zeuhz-Droid**
### Why: Write a C# program to divide two numbers codinasion/program#732

Closes codinasion/codinasion#90

### CODE REVIEW

**Comment by Zeuhz-Droid** [comment]
Hi hashraj, can you checkout my PR?

**Comment by Zeuhz-Droid** [comment]
Done

**Comment by victoriacheng15** [comment]
Please link the issues, not the PR.

Thank you!

**Comment by Zeuhz-Droid** [comment]
Done

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Beside missing `;` at line 9, the code looks great!

Thank you for contributing!

**Comment by Zeuhz-Droid** [comment]
Done.

**Review by victoriacheng15 — APPROVED** [review]

**Comment by victoriacheng15** [comment]
Thank you for contributing! 👍

**Pull request merged**
