### PR TITLE
Surface area of cuboid

### LINKED ISSUE #4458: Write a F# program to find surface area of a cuboid
### Description

Write a F# program to find surface area of a cuboid

Surface area of cuboid = 2 × (`Length` × `Width` + `Length` × `Height` + `Width` × `Height`)

```
Length : 2
Width  : 3
Height : 4

Surface area : 52
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSurfaceAreaOfACuboid.fs` file
- Add `FindSurfaceAreaOfACuboid.fs` file in `find-surface-area-of-a-cuboid` folder

</details>

### PR DESCRIPTION
**Pull request by anandfresh**
### Why:

Closes codinasion/codinasion#3355

### CODE REVIEW

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
the formula is not correct.

**Comment by anandfresh** [comment]
> the formula is not correct.

@victoriacheng15 please check the issue id for the formula , the same formula have used in this file

**Comment by victoriacheng15** [comment]
> > the formula is not correct.
> 
> @victoriacheng15 please check the issue id for the formula, the same formula has used in this file

Not quite the same, with the formula from your code, I got the output of 32. However, if you put an extra bracket like this ` 2 * ((length * width) + (length * height) + (width * height))` and this would give you the output of 52.

**Comment by anandfresh** [comment]
> > > the formula is not correct.
> > 
> > 
> > @victoriacheng15 please check the issue id for the formula, the same formula has used in this file
> 
> Not quite the same, with the formula from your code, I got the output of 32. However, if you put an extra bracket like this ` 2 * ((length * width) + (length * height) + (width * height))` and this would give you the output of 52.

@victoriacheng15  its fixed

**Review by victoriacheng15 — APPROVED** [review]

**Pull request merged**
