### PR TITLE
[Closed] Add files via upload

### LINKED ISSUE #4673: Write a Java program to print diamond pattern
### Description

Write a Java program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintDiamondPattern.java` file
- Add `PrintDiamondPattern.java` file in `print-diamond-pattern` folder

</details>

### PR DESCRIPTION
**Pull request by Aditya449930**
### Why:

Closes codinasion/codinasion#3546 

### What's being changed:
Added Java program File for Create Diamond pattern using Java language

### CODE REVIEW

**Comment by joao-vitor-souza** [comment]
Running multiple times I got some weirds results like:
```
* 
   * * 
  * * * 
 * * * * * * * * * 
* * * * * 
 * * * * 
  * * * 
   * * 
```
or:
```
* 
   * * 
  * * * 
 * * * * 
* * * * * 
* * * * * 
 * * * * * * * 
   * * 
```

**Comment by joao-vitor-souza** [comment]
Also, `!assign` your name in the issue

**Comment by Aditya449930** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Aditya449930, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Pull request closed without merging**
