### PR TITLE
[Closed] Revert 1 joelsathi hacktoberfest

### PR DESCRIPTION
**Pull request by joelsathi**
### Why:

Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@joelsathi I don't see any files?

**Comment by joelsathi** [comment]
I am really sorry. I forgot to add the files.

**Comment by victoriacheng15** [comment]
> I am really sorry. I forgot to add the files.

Still don't see files. It is probably better to recreate the branch and add your solutions. I just checked your rep, it seems messy, and it shows 0 changed files. 

Also, please make sure the issue is assigned to you. If it is not and no one was assigned, make sure type `!assign` in the issue.

Thank you!

**Comment by joelsathi** [comment]
> > I am really sorry. I forgot to add the files.
> 
> Still don't see files. It is probably better to recreate the branch and add your solutions. I just checked your rep, it seems messy, and it shows 0 changed files.
> 
> Also, please make sure the issue is assigned to you. If it is not and no one was assigned, make sure type `!assign` in the issue.
> 
> Thank you!

I will work on that and let you know!
Thank you for updating.

**Pull request closed without merging**
