### PR TITLE
[Closed] reverse of number in c++

### PR DESCRIPTION
**Pull request by palak-k5**
### Why:

Closes #ISSUE_NUMBER

### What's being changed:
added the code for reversing a number in c++

### CODE REVIEW

**Comment by palak-k5** [comment]
> 👋🏻 Hey @palak-k5
> 
> 💖 Thanks for opening this pull request 💖
> 
> This PR will be reviewed and merged shortly.

**Comment by palak-k5** [comment]
what does this mean may i know

**Comment by palak-k5** [comment]
i am a newbie  ,i did it by mistake

**Comment by victoriacheng15** [comment]
The issue is assigned to someone else. Please look for other issues to contribute. Make sure you type !assign to grab the issue

Thank you!

**Pull request closed without merging**
