### PR TITLE
Reveres number + docs fix #173 

### LINKED ISSUE #173: Reverse of a Number
### Title of article

Write a C# program to print reverse of a given number.

### Additional information

```
Input:  1234
Output: 4321
```

```
Input:  6512
Output: 2156
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Mrczarny**
### Why:

Closes #173 

### What's being changed:

- Added C# programme that reverses numbers 

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @Mrczarny 

Thanks for your contributions in this project 😃 

This PR will be merged soon

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Hey @Mrczarny 

There is some issue in `solution.cs`, please `fix` it

### Expected

```bash
Enter numbers : 1234
Reversed : 4321
```

### Actual result

```bash
Enter numbers : 1234

Unhandled Exception:
System.FormatException: Input string was not in a correct format.
  at System.Number.ThrowOverflowOrFormatException (System.Boolean overflow, System.String overflowResourceKey) [0x0001a] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Number.ParseInt32 (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles styles, System.Globalization.NumberFormatInfo info) [0x00016] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Int32.Parse (System.String s) [0x00016] in <533173d24dae460899d2b10975534bb0>:0 
  at Reverse.<Main>g__Reverse|0_0 (System.Int32 input) [0x00012] in <e778a0517c154aaf904a10a20e550393>:0 
  at Reverse.Main (System.String[] args) [0x00018] in <e778a0517c154aaf904a10a20e550393>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.FormatException: Input string was not in a correct format.
  at System.Number.ThrowOverflowOrFormatException (System.Boolean overflow, System.String overflowResourceKey) [0x0001a] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Number.ParseInt32 (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles styles, System.Globalization.NumberFormatInfo info) [0x00016] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Int32.Parse (System.String s) [0x00016] in <533173d24dae460899d2b10975534bb0>:0 
  at Reverse.<Main>g__Reverse|0_0 (System.Int32 input) [0x00012] in <e778a0517c154aaf904a10a20e550393>:0 
  at Reverse.Main (System.String[] args) [0x00018] in <e778a0517c154aaf904a10a20e550393>:0 
```

**Comment by Mrczarny** [comment]
Hey,
Sorry my bad. Just fixed it in a3a2ce37098648b1e4f662b0ee2310620b088eb5.

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by harshraj8843** [comment]
` Preview ` : https://codinasion--pr29-dev-mzwvnjuf.web.app/programme/reverse-of-a-number/

<sub>(expires Fri, 11 Mar 2022 03:09:29 GMT)</sub>

**Comment by harshraj8843** [comment]
` LIVE ` : https://codinasion.web.app/programme/reverse-of-a-number/

**Pull request merged**
