### PR TITLE
Update find_roots_of_quadratic_equation.dart

### PR DESCRIPTION
**Pull request by isyuricunha**
Improving code comprehension.

Changed this:

## 📑 Description

Closes #7540  

---

### Summary
📝🧹🗣️

Renamed variables in `find_roots_of_quadratic_equation.dart` to match the standard form of a quadratic equation. This improves the readability and clarity of the code.

> _`a`, `b`, `c` gone_
> _Quadratic equation clear_
> _Winter of bad names_

### Walkthrough
*  Rename variables to improve readability and clarity ([link](https://github.com/codinasion/program/pull/7541/files?diff=unified&w=0#diff-47dde8c75bc17a5a60ae006d9e07d17cc7e037f6a0d1d602142c87955e93d195L10-R30))

### CODE REVIEW

**Comment by isyuricunha** [comment]
!assign

**Comment by Killua-22** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @isyuricunha & @Killua-22 

The `!assign` command is only for `good first issue`

**Comment by isyuricunha** [comment]
Hi @harshraj8843 ,

I forget. Sorry. 

Kind Regards,
Yuri.

**Review by harshraj8843 — APPROVED** [review]
Thanks for the improvement 👍🏻

**Pull request merged**
