### PR TITLE
[Closed] Added cpp solution for find-area-of-a-square

### LINKED ISSUE #432: Find area of a square
### Description

Write a program to find area of a square

Area of square = `Side`^2

```
Side : 2

Area : 4
```

### Tracking Issues

- [ ] Write a C program to find area of a square
- [ ] Write a C# program to find area of a square
- [ ] Write a C++ program to find area of a square
- [ ] Write a Dart program to find area of a square
- [ ] Write a F# program to find area of a square
- [ ] Write a GO program to find area of a square
- [ ] Write a Java program to find area of a square
- [ ] Write a JavaScript program to find area of a square
- [ ] Write a Julia program to find area of a square
- [ ] Write a Kotlin program to find area of a square
- [ ] Write a Perl program to find area of a square
- [ ] Write a PHP program to find area of a square
- [ ] Write a Python program to find area of a square
- [ ] Write a R program to find area of a square
- [ ] Write a Ruby program to find area of a square
- [ ] Write a Rust program to find area of a square
- [ ] Write a Scala program to find area of a square
- [ ] Write a Swift program to find area of a square
- [ ] Write a TypeScript program to find area of a square

### PR DESCRIPTION
**Pull request by destroyer5067**
find-area-of-a-square CPP solution added

closes codinasion/codinasion#358

### CODE REVIEW

**Comment by victoriacheng15** [comment]
Hi @destroyer5067,

The issue you linked is an issue for the program, not language specific. Please link the language specific issue.

Thank you!

**Review by victoriacheng15 — COMMENTED** [review]
Looks good.

Thank you for contributing! 👍

**Comment by destroyer5067** [comment]
Okay, Didn't noticed , i am correcting the issue rightnow

**Comment by destroyer5067** [comment]
find-area-of-a-square CPP solution added

closes codinasion/codinasion#361

**Comment by destroyer5067** [comment]
@victoriacheng15  i corrected the issue trackid , now you can review

Thanks for your suggestion

**Comment by destroyer5067** [comment]
Update,

FindMaximumOfNNumbers.cpp added

closes codinasion/codinasion#561

**Comment by destroyer5067** [comment]
So basically i added two solutions here,

FindAreaOfASquare.cpp                             closes codinasion/codinasion#361 
FindMaximumOfNNumbers.cpp                 closes codinasion/codinasion#561 


Just to avoid any confusion

**Comment by victoriacheng15** [comment]
Hey @destroyer5067,

😅 Sorry, I just noticed that you are pushing from the master branch. Please create a branch and then add two solutions you have done. You can refer steps [here](https://github.com/codinasion/program/blob/master/CONTRIBUTING.md#make-changes).

Thank you!

**Comment by destroyer5067** [comment]
@victoriacheng15  sorry for the same, i will redo  this as suggested

**Pull request closed without merging**
