### PR TITLE
:sparkles: add ConvertStringToPascalcase/java

### LINKED ISSUE #4093: Write a Java program to convert string to pascalcase
### Description

Write a Java program to convert string to pascalcase

Pascalcase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "HelloWorld"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToPascalcase.java` file
- Add `ConvertStringToPascalcase.java` file in `convert-string-to-pascalcase` folder

</details>

### PR DESCRIPTION
**Pull request by Arbaz23**
### Why:

Closes codinasion/codinasion#3043

### CODE REVIEW

**Comment by joao-vitor-souza** [comment]
Please, make a reference to the issue you're trying to close.

**Comment by joao-vitor-souza** [comment]
I just ran your program, and it does not return a Pascal case converted string. `hello world`, for instance, returns `Hello World`, and not `HelloWorld`.

**Comment by Arbaz23** [comment]
@joao-vitor-souza Hello, sorry now it's good, you can check the new commit

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
