### PR TITLE
Write a C++ program to find perimeter of a square

### LINKED ISSUE #3670: Find perimeter of a square
### Description

Write a program to find perimeter of a square

Perimeter of square = 4 × `Side`

```
Side : 2

Perimeter : 8
```

### Tracking Issues

- [ ] Write a C program to find perimeter of a square
- [ ] Write a C# program to find perimeter of a square
- [ ] Write a C++ program to find perimeter of a square
- [ ] Write a Dart program to find perimeter of a square
- [ ] Write a F# program to find perimeter of a square
- [ ] Write a GO program to find perimeter of a square
- [ ] Write a Haskell program to find perimeter of a square
- [ ] Write a Java program to find perimeter of a square
- [ ] Write a JavaScript program to find perimeter of a square
- [ ] Write a Julia program to find perimeter of a square
- [ ] Write a Kotlin program to find perimeter of a square
- [ ] Write a Perl program to find perimeter of a square
- [ ] Write a PHP program to find perimeter of a square
- [ ] Write a Python program to find perimeter of a square
- [ ] Write a R program to find perimeter of a square
- [ ] Write a Ruby program to find perimeter of a square
- [ ] Write a Rust program to find perimeter of a square
- [ ] Write a Scala program to find perimeter of a square
- [ ] Write a Swift program to find perimeter of a square
- [ ] Write a TypeScript program to find perimeter of a square

### LINKED ISSUE #3673: Write a C++ program to find perimeter of a square
### Description

Write a C++ program to find perimeter of a square

Perimeter of square = 4 × `Side`

```
Side : 2

Perimeter : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindPerimeterOfASquare.cpp` file
- Add `FindPerimeterOfASquare.cpp` file in `find-perimeter-of-a-square` folder

</details>

### PR DESCRIPTION
**Pull request by sureshsgith**
### Why:

Closes codinasion/codinasion#2701

### CODE REVIEW

**Review by grraghav120 — DISMISSED** [review]
Closes both issues

**Comment by sureshr3git** [comment]
@grraghav120 why I close my issues

**Comment by victoriacheng15** [comment]
@sureshr3git 

The issue is only for cpp program, and need you to link python program issue. 

Thank you!

**Comment by sureshsgith** [comment]
@victoriacheng15 
issue codinasion/codinasion#2740 
pr codinasion/program#3396

**Comment by victoriacheng15** [comment]
> @victoriacheng15 
> issue codinasion/codinasion#2740 
> pr codinasion/program#3396 

The find average digit program issue exists. It was assigned to someone else and is closed now.  So, please remove the python file. 

Thank you.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
