### PR TITLE
add decimal_to_binary.rb

### LINKED ISSUE #3862: Write a Ruby program to convert decimal to binary
### Description

Write a Ruby program to convert decimal to binary

Binary is a base-2 number system. It uses only two digits: 0 and 1. The digits are called bits. A bit is the smallest unit of information in a computer. A bit can be either 0 or 1. A bit can be used to represent a single value, such as 0 or 1, or it can be used to represent a single state, such as on or off.

To convert a decimal number to binary, we can use the following algorithm:

1. Divide the decimal number by 2.
2. Write down the remainder.
3. Divide the quotient by 2.
4. Write down the remainder.
5. Repeat steps 3 and 4 until the quotient is 0.
6. The binary number is the sequence of remainders written in reverse order.

```
Input  : 10
Output : 1010
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDecimalToBinary.rb` file
- Add `ConvertDecimalToBinary.rb` file in `convert-decimal-to-binary` folder

</details>

### PR DESCRIPTION
**Pull request by rafaover**
### Why:

Closes codinasion/codinasion#2841

### What's being changed:

Added solution decimal_to_binary.rb codinasion/codinasion#2841

### CODE REVIEW

**Review by anandfresh — APPROVED** [review]

**Review by hi-Kartik2004 — CHANGES_REQUESTED** [review]
Hi @rafaover, firstly thanks for linking the issue and making a pull request (PR).
Whenever I run your code it doesn't print anything, reference image is attached below.
Can you resolve this?

image

**Comment by rafaover** [comment]
My bad, gonna update. Thanks for the warning.

**Comment by rafaover** [comment]
Code Updated. :)

**Review by hi-Kartik2004 — APPROVED** [review]

**Comment by hi-Kartik2004** [comment]
Thanks for contributing @rafaover !!

**Pull request merged**
