### PR TITLE
[Fix] dark mode toggle bug

### LINKED ISSUE #4: Fix Darkmode Toggle
Darkmode Toggle is not working correctly.

Few bugs:
- Double-click to activate for the first-time visitor
- Sometimes, it stops working and one has to reload the page to make it work again
	- For example, on navigation from `home` to `/contributors`

### PR DESCRIPTION
**Pull request by alindsharmasimply**
### Why:

This PR is linked to an issue.
Closes #4 

### What's being changed:
* Condition that checks the initial theme mode on page load.

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @alindsharmasimply 

Thanks for your contributions, but it seems like it is still not working for the first time visitor(has to double-click click icon)

### Way to produce

- open [`https://codinasion-git-fork-alindsharmasimply-bug-dar-090906-codinasion.vercel.app`](https://codinasion-git-fork-alindsharmasimply-bug-dar-090906-codinasion.vercel.app/) in incognito window

**Review by 0ME9A — COMMENTED** [review]
If you are not using localhost then I don't think it will work perfectly😒

**Comment by harshraj8843** [comment]
On localhost also, it's not working 😞

**Comment by 0ME9A** [comment]
> On localhost also, it's not working 😞

I think it's working fine.


https://user-images.githubusercontent.com/83957658/219857254-cdd96ee8-7359-4275-be50-c3421a58a5ec.mp4

**Review by 0ME9A — APPROVED** [review]
Approved

**Comment by 0ME9A** [comment]
Hey @harshraj8843,
Do you know that I've also developed [something](https://red-magic.vercel.app/), but these days I'm extremely busy, so I didn't expose it.

**Comment by harshraj8843** [comment]
Yes, I was also waiting for this 🤩  

My plan is to merge these two projects together, because from now onward most of the projects will be deployed on `codinasion.org`

**Comment by harshraj8843** [comment]
We can do that right?

**Comment by 0ME9A** [comment]
> Yes, I was also waiting for this 🤩
> 
> My plan is to merge these two projects together, because from now onward most of the projects will be deployed on `codinasion.org`

**deployed on codinasion.org** How, Can you explain more?🤔

**Comment by harshraj8843** [comment]
Most of our projects are not complete website projects. It contains code or package or similar things.

For example, the `program` repo contains the program `solution files` and the program website code will be available inside this repo

> **Note** Not all projects can be hosted here. For example `codinasion-tools` will be not affected by this, because it is a complete project (thanks to you 👏🏻 )
>
> But we can deploy a mini version of tools here for the showcase

### Reasons

- Easier to Maintain
- Easier to share components
- Good for SEO

**Comment by harshraj8843** [comment]
> I think it's working fine.

Please open the website in an incognito window and then test (as a new visitor)

**Comment by 0ME9A** [comment]
> 



> > I think it's working fine.
> 
> Please open the website in an incognito window and then test (as a new visitor)

let me check

**Comment by alindsharmasimply** [comment]
Have applied a check to remove hydration errors.

**Comment by harshraj8843** [comment]
Issue fixed in #7

**Pull request closed without merging**
