### PR TITLE
add recursive code for c

### LINKED ISSUE #482: Write a C program to find sum of squares of numbers by recursion
### Description

Write a C program to find sum of squares of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfSquaresOfNumbersByRecursion.c` file
- Add `FindSumOfSquaresOfNumbersByRecursion.c` file in `find-sum-of-squares-of-numbers-by-recursion` folder

</details>

### PR DESCRIPTION
**Pull request by Ritesh-Dabral**
Signed-off-by: Ritesh Dabral <riteshdabral1@gmail.com>

### Why:

codinasion/codinasion#398

codinasion/codinasion#399

Closes #ISSUE_NUMBER
Closes codinasion/codinasion#399 
### What's being changed:
Add logic to find the sq of sum using recursive approach for 'C'

### CODE REVIEW

**Comment by Ritesh-Dabral** [comment]
@PrajwalBorkar @victoriacheng15
Please review

**Comment by Ritesh-Dabral** [comment]
@victoriacheng15 @PrajwalBorkar 
Please verify and merge this PR

**Comment by victoriacheng15** [comment]
@Ritesh-Dabral Please dont ping us for review. We will review when we are able to do so. Thank you!

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
