### PR TITLE
print-inverted-pyramid-pattern.py

### LINKED ISSUE #5006: Write a Python program to print inverted pyramid pattern
### Description

Write a Python program to print inverted pyramid pattern

```
Input   : 5

Output : 
1 2 3 4 5
1 2 3 4 
1 2 3
1 2
1
```

<sub>Contributed by - @PraaneshSelvaraj</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `print-inverted-pyramid-pattern.py` file
- Add `print-inverted-pyramid-pattern.py` file in `program/print-inverted-pyramid-pattern` folder

</details>

### PR DESCRIPTION
**Pull request by Medmly20208**
### Why:

Closes codinasion/codinasion#3665

### CODE REVIEW

**Review by anandfresh — APPROVED** [review]

**Comment by Medmly20208** [comment]
@anandfresh the pull request didn't get merged.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Comment by harshraj8843** [comment]
@Medmly20208 PR needs to be approved by 2 reviewers to ensure that there is no issue with `Linked Issue(s)` and `code` 🤗

**Comment by Medmly20208** [comment]
@harshraj8843 okay I got you thanks .

**Pull request merged**
