### PR TITLE
Created splitStringIntoArrayOfWords.scala

### LINKED ISSUE #5656: Write a Scala program to split string into array of words
### Description

Write a Scala program to split string into array of words

```
Input  : "hello world"
Output : ["hello", "world"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `splitStringIntoArrayOfWords.scala` file
- Add `splitStringIntoArrayOfWords.scala` file in `program/split-string-into-array-of-words` folder

</details>

### PR DESCRIPTION
**Pull request by patel-aum**
### Why:

Closes codinasion/codinasion#4302 

### What's being changed:
Added splitStringIntoArrayOfWords.scala

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
@patel-aum  Please assign the issue (#5656) to your name before raising a PR

**Comment by patel-aum** [comment]
> @patel-aum Please assign the issue (#5656) to your name before raising a PR

okayy

**Comment by patel-aum** [comment]
> > @patel-aum Please assign the issue (#5656) to your name before raising a PR
> 
> okayy

next time i will

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
