### PR TITLE
Editedfile

### LINKED ISSUE #1963: Write a Python program to convert binary to decimal
### Description

Write a Python program to convert binary to decimal

Binary is a base-2 number system. It uses only two digits: 0 and 1. The digits are called bits. A bit is the smallest unit of information in a computer. A bit can be either 0 or 1. A bit can be used to represent a single value, such as 0 or 1, or it can be used to represent a single state, such as on or off.

To convert a binary number to decimal, we can use the following algorithm:

1. Multiply the first bit by 2^0.
2. Multiply the second bit by 2^1.
3. Multiply the third bit by 2^2.
4. Multiply the fourth bit by 2^3.
5. Repeat steps 3 and 4 until the last bit.
6. Add the results of all the multiplications.
7. The decimal number is the sum of all the multiplications.

```
Input  : 1010
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-binary-to-decimal.py` file
- Add `convert-binary-to-decimal.py` file in `convert-binary-to-decimal` folder

</details>

### PR DESCRIPTION
**Pull request by bbhoom**
### Why:

Closes codinasion/codinasion#1557  

### What's being changed:
python file from decimal to binary 
code files from my branch have been added below.

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@bbhoom 

Please link language-specific issues for both, and not the closed PR.

Thank you!

**Comment by bbhoom** [comment]
issue codinasion/program#1972 has been closed but not merged , may i know why it hasnt been merged?

**Comment by victoriacheng15** [comment]
@bbhoom I stated the reason in the PR. You were pushing changes from the master branch, which is not recommended. Please check out [CONTRIBUTING.md](https://github.com/codinasion/program/blob/master/CONTRIBUTING.md) for more details on `make changes section`.

Thank you!

**Review by victoriacheng15 — APPROVED** [review]
Looks good!

Thank you for contributing!

**Pull request merged**
