### PR TITLE
Added calculate permutations.... for multiple languages.

### LINKED ISSUE #4200: Write a GO program to calculate the permutation of n objects taken r at a time
### Description

Write a GO program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/calculate_the_permutation_of_n_objects_taken_r_at_a_time.go` file
- Add `calculate_the_permutation_of_n_objects_taken_r_at_a_time.go` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

### LINKED ISSUE #4202: Write a Java program to calculate the permutation of n objects taken r at a time
### Description

Write a Java program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CalculateThePermutationOfNObjectsTakenRAtATime.java` file
- Add `CalculateThePermutationOfNObjectsTakenRAtATime.java` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

### LINKED ISSUE #4203: Write a JavaScript program to calculate the permutation of n objects taken r at a time
### Description

Write a JavaScript program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CalculateThePermutationOfNObjectsTakenRAtATime.js` file
- Add `CalculateThePermutationOfNObjectsTakenRAtATime.js` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

### LINKED ISSUE #4208: Write a Python program to calculate the permutation of n objects taken r at a time
### Description

Write a Python program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/calculate-the-permutation-of-n-objects-taken-r-at-a-time.py` file
- Add `calculate-the-permutation-of-n-objects-taken-r-at-a-time.py` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

### LINKED ISSUE #4211: Write a Rust program to calculate the permutation of n objects taken r at a time
### Description

Write a Rust program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/calculate_the_permutation_of_n_objects_taken_r_at_a_time.rs` file
- Add `calculate_the_permutation_of_n_objects_taken_r_at_a_time.rs` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

### LINKED ISSUE #4212: Write a Scala program to calculate the permutation of n objects taken r at a time
### Description

Write a Scala program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/calculateThePermutationOfNObjectsTakenRAtATime.scala` file
- Add `calculateThePermutationOfNObjectsTakenRAtATime.scala` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

### LINKED ISSUE #4214: Write a TypeScript program to calculate the permutation of n objects taken r at a time
### Description

Write a TypeScript program to calculate the permutation of n objects taken r at a time

Permutation is an arrangement of objects in a particular order. The number of permutations on n objects taken r at a time is given by the formula n!/(n-r)!

```
Input  : 5, 2
Output : 20
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CalculateThePermutationOfNObjectsTakenRAtATime.ts` file
- Add `CalculateThePermutationOfNObjectsTakenRAtATime.ts` file in `calculate-the-permutation-of-n-objects-taken-r-at-a-time` folder

</details>

### PR DESCRIPTION
**Pull request by BrokenDesign**
### Why:
* Closes codinasion/codinasion#3125
* Closes codinasion/codinasion#3127
* Closes codinasion/codinasion#3128
* Closes codinasion/codinasion#3136
* Closes codinasion/codinasion#3137
* Closes codinasion/codinasion#3139

### What's being changed:
Added the below files
```ps
program\calculate-the-permutation-of-n-objects-taken-r-at-a-time

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ---- 
-a----        10/15/2022  12:55 PM            922 CalculateThePermutationOfNObjectsTakenRAtATime.java
-a----        10/15/2022  12:55 PM            281 CalculateThePermutationOfNObjectsTakenRAtATime.js
-a----        10/15/2022  12:55 PM            434 calculateThePermutationOfNObjectsTakenRAtATime.scala
-a----        10/15/2022  11:58 AM            410 CalculateThePermutationOfNObjectsTakenRAtATime.ts
-a----        10/15/2022  12:55 PM            617 calculate_the_permutation_of_n_objects_taken_r_at_a_time.go
-a----        10/15/2022  12:56 PM            502 calculate_the_permutation_of_n_objects_taken_r_at_a_time.rs
```

### CODE REVIEW

**Comment by joao-vitor-souza** [comment]
Please, assign first in codinasion/codinasion#3133

**Comment by BrokenDesign** [comment]
I thought I was. I just tried but someone else is assigned to that one.

**Comment by BrokenDesign** [comment]
Do you want me to close and resubmit without that file?

**Comment by joao-vitor-souza** [comment]
> Do you want me to close and resubmit without that file?

It's not needed. I edited your PR.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
