### PR TITLE
[Closed] [#3380] Created The FindTheRankOfAMatrix.java

### PR DESCRIPTION
**Pull request by NavneetBende**
### Why:

Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by NavneetBende** [comment]
Hello There Please review my request,
Thank You

**Review by hi-Kartik2004 — CHANGES_REQUESTED** [review]
Hi @NavneetBende, Firstly thanks for making a PR.
But seems like you've forgotten to link the issue number your pull request solves in your first/ top-most comment, can you edit your comment and add the `issue id` your PR solves, also change your file name to `FindTheRankOfAMatrix.java` Pascal Case.

**Comment by NavneetBende** [comment]
Sure I'll do that ASAP

**Comment by harshraj8843** [comment]
Issue codinasion/codinasion#2495 has already closed

**Pull request closed without merging**
