### PR TITLE
Code in PHP

### LINKED ISSUE #2057: Write a PHP program to convert string to pathcase
### Description

Write a PHP program to convert string to pathcase

Pathcase is a style of writing in which all letters are lowercase and spaces are replaced with forward slashes.

```
Input  : "hello world"
Output : "hello/world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_pathcase.php` file
- Add `convert_string_to_pathcase.php` file in `convert-string-to-pathcase` folder

</details>

### LINKED ISSUE #2744: Convert string to pathcase
### Description

Write a program to convert string to pathcase

Pathcase is a style of writing in which all letters are lowercase and spaces are replaced with forward slashes.

```
Input  : "hello world"
Output : "hello/world"
```

### Tracking Issues

- [ ] Write a C program to convert string to pathcase
- [ ] Write a C# program to convert string to pathcase
- [ ] Write a C++ program to convert string to pathcase
- [ ] Write a Dart program to convert string to pathcase
- [ ] Write a F# program to convert string to pathcase
- [ ] Write a GO program to convert string to pathcase
- [ ] Write a Haskell program to convert string to pathcase
- [ ] Write a Java program to convert string to pathcase
- [ ] Write a JavaScript program to convert string to pathcase
- [ ] Write a Julia program to convert string to pathcase
- [ ] Write a Kotlin program to convert string to pathcase
- [ ] Write a Perl program to convert string to pathcase
- [ ] Write a PHP program to convert string to pathcase
- [ ] Write a Python program to convert string to pathcase
- [ ] Write a R program to convert string to pathcase
- [ ] Write a Ruby program to convert string to pathcase
- [ ] Write a Rust program to convert string to pathcase
- [ ] Write a Scala program to convert string to pathcase
- [ ] Write a Swift program to convert string to pathcase
- [ ] Write a TypeScript program to convert string to pathcase

### LINKED ISSUE #2757: Write a PHP program to convert string to pathcase
### Description

Write a PHP program to convert string to pathcase

Pathcase is a style of writing in which all letters are lowercase and spaces are replaced with forward slashes.

```
Input  : "hello world"
Output : "hello/world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_pathcase.php` file
- Add `convert_string_to_pathcase.php` file in `convert-string-to-pathcase` folder

</details>

### PR DESCRIPTION
**Pull request by Nitya-Pasrija**
### Why:

Closes codinasion/codinasion#2057 

### What's being changed:
Code file for Converting string to pathcase in php

### CODE REVIEW

**Comment by Nitya-Pasrija** [comment]
Heya @harshraj8843 this branch is becoming out-of-date, so do I keep on updating it?

**Comment by harshraj8843** [comment]
> Heya @harshraj8843 this branch is becoming out-of-date, so do I keep on updating it?

No, it will be auto-updated before merging 🤗

**Comment by victoriacheng15** [comment]
@Nitya-Pasrija 

Please link language-specific issue.

Thank you!

**Comment by Nitya-Pasrija** [comment]
Closes codinasion/codinasion#2057

**Comment by Nitya-Pasrija** [comment]
@victoriacheng15 
My bad. I have linked the right issue now :)

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
