### PR TITLE
Added fahrenheit to kelvin conversion program

### LINKED ISSUE #4413: Write a C# program to convert fahrenheit to kelvin
### Description

Write a C# program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFahrenheitToKelvin.cs` file
- Add `ConvertFahrenheitToKelvin.cs` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

### PR DESCRIPTION
**Pull request by KyleMcIndoe**
### Why:

Closes codinasion/codinasion#4413

Conversion I need frequently, and I didnt see it here

### What's being changed:

Added new folder with csharp program

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
@KyleMcIndoe can you please add the issue id to this PR

**Comment by KyleMcIndoe** [comment]
> @KyleMcIndoe can you please add the issue id to this PR

Doesnt solve an existing issue

Will close PR if you want

**Comment by anandfresh** [comment]
> @KyleMcIndoe can you please add the issue id to this PR

**Comment by anandfresh** [comment]
> > @KyleMcIndoe can you please add the issue id to this PR
> 
> Doesnt solve an existing issue
> 
> Will close PR if you want

Hi @KyleMcIndoe  , recommend you to create an issue if it doesn't exists and then tag the issue id to this PR

**Comment by KyleMcIndoe** [comment]
Why:

Solves issue num codinasion/codinasion#4410

Conversion I need frequently, and I didnt see it here

What's being changed:
Added new folder with csharp program

**Review by anandfresh — APPROVED** [review]

**Pull request merged**
