### PR TITLE
Java area of trapezoid

### LINKED ISSUE #420: Fibonacci Pattern
### Title of article

Write a Java program to print Fibonacci pattern.

### Additional information

`Input` : `5`

`Output` : 
```
1
1 1	
1 1 2	
1 1 2 3	
1 1 2 3 5
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### LINKED ISSUE #501: Area of a trapezoid
### Title of article

Write a Java program that to compute area of trapezoid

Area of a trapezoid = ( ` base 1 ` + ` base 2 ` ) * ` height ` / 2

### Example:

Base 1 = 5, Base 2 = 10, Height = 7

Area of the trapezoid = (5+10)*7/2 = 52.5

### Additional information

```
Base 1 : 5
Base 2 : 10
Height  : 7

Area : 52.5
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Anzo52**
### Why: Move java file to programme folder

Closes #501 
Closes #420

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by Anzo52 — COMMENTED** [review]
New PR, hopefully got it right this time.

**Review by Anzo52 — COMMENTED** [review]
:+1:

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by harshraj8843** [comment]
https://codinasion.web.app/programme/area-of-trapezoid/

https://codinasion.web.app/programme/fibonacci-pattern/

**Review by Anzo52 — COMMENTED** [review]
:+1:

**Pull request merged**
