### PR TITLE
Factorial of a number in JS

### LINKED ISSUE #790: Write a JavaScript program to find factorial of a number by recursion
### Description

Write a JavaScript program to find factorial of a number by recursion

Factorial of a number is the product of all the numbers from 1 to that number. For example, factorial of 5 is 5\*4\*3\*2\*1 = 120.

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindFactorialOfANumberByRecursion.js` file
- Add `FindFactorialOfANumberByRecursion.js` file in `find-factorial-of-a-number-by-recursion` folder

</details>

### PR DESCRIPTION
**Pull request by greeshma-d**
Closes codinasion/codinasion#647 

### What's being changed:
Added javascript file to return factorial of a number

### CODE REVIEW

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Please update filename to `FindFactorialOfANumberByRecursion.js`

**Comment by greeshma-d** [comment]
Updated

**Review by victoriacheng15 — APPROVED** [review]
Looks good.

Thank you for contributing!

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
