### PR TITLE
print number to words

### LINKED ISSUE #2614: Write a C program to print number to words
### Description

Write a C program to print number to words

```
Input  : 123456789
Output : One Hundred Twenty Three Million Four Hundred Fifty Six Thousand Seven Hundred Eighty Nine
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintNumberToWords.c` file
- Add `PrintNumberToWords.c` file in `print-number-to-words` folder

</details>

### PR DESCRIPTION
**Pull request by manyadua16**
c-based program to convert string to lower case
closes codinasion/codinasion#1940

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@manyadua16 

Please link language-specific issue in the first comment.

Thank you!

**Comment by manyadua16** [comment]
is this alright?

**Comment by victoriacheng15** [comment]
> is this alright?

The number leads me to this pull request. The number need to be the `issue` that you are contributing to. 

If you don't remember the issue number, you can
- go to `issue` tab
- look for `Assignee`
- type your GitHub username
- find the issue that is related to this pull request.
- type `Closes #ISSUE_NUMBER` in the first comment

image


Thank you!

**Comment by manyadua16** [comment]
I have made the necessary changes, please tell me if any more corrections are required!

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
