### PR TITLE
[Closed] added program to convert meters to miles in js

### LINKED ISSUE #277: Convert meters to miles
### Description

Write a program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```

### Tracking Issues

- [ ] Write a C program to convert meters to miles
- [ ] Write a C# program to convert meters to miles
- [ ] Write a C++ program to convert meters to miles
- [ ] Write a Dart program to convert meters to miles
- [ ] Write a F# program to convert meters to miles
- [ ] Write a GO program to convert meters to miles
- [ ] Write a Java program to convert meters to miles
- [ ] Write a JavaScript program to convert meters to miles
- [ ] Write a Julia program to convert meters to miles
- [ ] Write a Kotlin program to convert meters to miles
- [ ] Write a Perl program to convert meters to miles
- [ ] Write a PHP program to convert meters to miles
- [ ] Write a Python program to convert meters to miles
- [ ] Write a R program to convert meters to miles
- [ ] Write a Ruby program to convert meters to miles
- [ ] Write a Rust program to convert meters to miles
- [ ] Write a Scala program to convert meters to miles
- [ ] Write a Swift program to convert meters to miles
- [ ] Write a TypeScript program to convert meters to miles

### LINKED ISSUE #285: Write a JavaScript program to convert meters to miles
### Description

Write a JavaScript program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMetersToMiles.js` file
- Add `ConvertMetersToMiles.js` file in `convert-meters-to-miles` folder

</details>

### PR DESCRIPTION
**Pull request by MusabMuhie**
### Why:

Closes codinasion/codinasion#266 

> edited: point to the JS specific isse.

### What's being changed:
Added JS program to convert meters to miles

### CODE REVIEW

**Review by victoriacheng15 — COMMENTED** [review]
Hey @MusabMuhie,

The function looks good. However, I noticed that you did not create a separated branch. Please refer to the `Make Changes` section in [CONTRIBUTING.md](https://github.com/codinasion/program/blob/master/CONTRIBUTING.md). 

Also, next time, please type `!assign` in the issue that you would like to work on.  For this, please refer to the [README](https://github.com/codinasion/program/blob/master/README.md). 

Keep in mind, the issue you just linked is the general issue that keep tracks of which languages that has not done yet. You would want to point to the language specific issue. For JavaScript, It would be `Write a JavaScript program to......`. You can find specific issue with `JavaScript `label or any language that you would like to work on

image

**Comment by MusabMuhie** [comment]
Hey @victoriacheng15,

Thanks for the review. Should I close my pull request and redo it with a pull request from a separate branch? And when you say link to specific language, is that the closes hashtag285 tag?

**Comment by victoriacheng15** [comment]
> Hey @victoriacheng15,
> 
> Thanks for the review. Should I close my pull request and redo it with a pull request from a separate branch? And when you say link to specific language, is that the closes hashtag285 tag?

Highly recommended starting over and create a branch. You could check out this [blog](https://dev.to/codesphere/how-to-start-contributing-to-open-source-projects-on-github-534n) for steps if you needed.

And yes, the 285 is the issue.

Let me know if I am not clear, or you have more questions. :D

**Comment by harshraj8843** [comment]
Hey @MusabMuhie 

Please comment `!assign` on codinasion/codinasion#266 to be auto-assigned, to prevent any conflict

```
!assign
```

Thanks 👍🏻

**Pull request closed without merging**
