### PR TITLE
Dart/convert binary to decimal

### LINKED ISSUE #1953: Write a Dart program to convert binary to decimal
### Description

Write a Dart program to convert binary to decimal

Binary is a base-2 number system. It uses only two digits: 0 and 1. The digits are called bits. A bit is the smallest unit of information in a computer. A bit can be either 0 or 1. A bit can be used to represent a single value, such as 0 or 1, or it can be used to represent a single state, such as on or off.

To convert a binary number to decimal, we can use the following algorithm:

1. Multiply the first bit by 2^0.
2. Multiply the second bit by 2^1.
3. Multiply the third bit by 2^2.
4. Multiply the fourth bit by 2^3.
5. Repeat steps 3 and 4 until the last bit.
6. Add the results of all the multiplications.
7. The decimal number is the sum of all the multiplications.

```
Input  : 1010
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_binary_to_decimal.dart` file
- Add `convert_binary_to_decimal.dart` file in `convert-binary-to-decimal` folder

</details>

### PR DESCRIPTION
**Pull request by auleki**
Closes codinasion/codinasion#1547

### What's being changed:
This is a function that takes a base 2 number and returns a base 10 equivalent

### CODE REVIEW

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Copied and pasted onto replit online editor and the code doesn't work for me. Please double-check to see if the code can run or not on your end.

image

Thank you!

**Comment by auleki** [comment]
Yeah @victoriacheng15 it needs you to add a `main.dart` file. I'll add that for you shortly.

Thanks for your feedback.

**Comment by victoriacheng15** [comment]
@auleki can you make it run with one file only?

**Comment by auleki** [comment]
@victoriacheng15 sure. I've made that correction. Give it a shot

**Review by victoriacheng15 — APPROVED** [review]
Looks good!

Thank you for contributing!

**Pull request merged**
