### PR TITLE
Hello world in Typescript

### LINKED ISSUE #21: Write a TypeScript program to print hello world
### Description

Write a TypeScript program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.ts` file
- Add `PrintHelloWorld.ts` file in `print-hello-world` folder

</details>

### LINKED ISSUE #22: Write a TypeScript program to print hello world
### Description

Write a TypeScript program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.ts` file
- Add `PrintHelloWorld.ts` file in `print-hello-world` folder

</details>

### PR DESCRIPTION
**Pull request by anaskhan28**
### Why:
Closes codinasion/codinasion#22 

### What's being changed:
Added hello world in Typescript

### CODE REVIEW

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Please follow the naming convention from `how to contribute` dropdown in the issue.

Thank you!

**Comment by anaskhan28** [comment]
done

**Review by victoriacheng15 — APPROVED** [review]
Awesome! 

Thank you for contributing! 👍

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
