### PR TITLE
[Closed] Fixed bug in rename.py script

### LINKED ISSUE #5079: Write a C++ program to print numbers from 1 to n without using a loop
### Description

Write a C++ program to print numbers from 1 to n without using a loop

```
Input  : 5
Output : 1 2 3 4 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintNumbersFrom1ToNWithoutUsingALoop.cpp` file
- Add `PrintNumbersFrom1ToNWithoutUsingALoop.cpp` file in `program/print-numbers-from-1-to-n-without-using-a-loop` folder

</details>

### LINKED ISSUE #5253: Write a C++ program to find sum of squares of numbers
### Description

Write a C++ program to find sum of squares of numbers

Suppose you have a list of numbers, and you want to find the sum of the squares of those numbers. For example, if you have the list `[1, 2, 3]`, you want to find the sum of the squares of those numbers, which is `1^2 + 2^2 + 3^2 = 14`.

```
Input  : 1 2 3 4 5
Output : 55
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfSquaresOfNumbers.cpp` file
- Add `FindSumOfSquaresOfNumbers.cpp` file in `program/find-sum-of-squares-of-numbers` folder

</details>

### LINKED ISSUE #5340: Write a C++ program to find sum of n natural numbers using formula
### Description

Write a C++ program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfNNaturalNumbersUsingFormula.cpp` file
- Add `FindSumOfNNaturalNumbersUsingFormula.cpp` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

### LINKED ISSUE #5405: Write a C++ program to find sum of digits of a number
### Description

Write a C++ program to find sum of digits of a number

Suppose you have a number `n` and you want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

```
Input  : 123
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfDigitsOfANumber.cpp` file
- Add `FindSumOfDigitsOfANumber.cpp` file in `program/find-sum-of-digits-of-a-number` folder

</details>

### LINKED ISSUE #5426: Write a C++ program to merge two strings
### Description

Write a C++ program to merge two strings

```
Input  : ABC DEF
Output : ABCDEF
```
<details>
<summary>How to contribute</summary>

- Save the solution in `MergeTwoStrings.cpp` file
- Add `MergeTwoStrings.cpp` file in `program/merge-two-strings` folder

</details>

### LINKED ISSUE #5513: Write a C++ program to convert weeks to days
### Description

Write a C++ program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToDays.cpp` file
- Add `ConvertWeeksToDays.cpp` file in `program/convert-weeks-to-days` folder

</details>

### LINKED ISSUE #5809: `BUG` Rename File Script
### Description

The [`rename file script`](https://github.com/codinasion/program/blob/master/scripts/rename_files.py) is creating new files instead of renaming them

https://github.com/codinasion/program/blob/ad631886f3a8a59df7e10e0a2edb3b5493669a0d/scripts/rename_files.py#L72-L80

### Additional information

See 👉🏻 https://github.com/codinasion/program/commit/ad631886f3a8a59df7e10e0a2edb3b5493669a0d

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by hi-Kartik2004**
### Why:
Closes codinasion/codinasion#4311
Same as pull request codinasion/program#5811
Closes codinasion/codinasion#4161
Closes codinasion/codinasion#4076
Closes codinasion/codinasion#3907
Closes codinasion/codinasion#3991
Closes codinasion/codinasion#4055
Closes codinasion/codinasion#3738

### What's being changed:
Added a new **feature to check for duplicate files in a program folder and added an option for the organizer to delete the duplicate file if he wishes to.**

As you can see in this image there is a duplicate file named simply.cpp
image

After running the rename.py script, The terminal looks like this: 
image

After confirming to delete the duplicate file
image

The file gets deleted :)
image

Contributed by:
Kartikeya Saini

### CODE REVIEW

**Comment by harshraj8843** [comment]
Thanks for the solution with the explanation 👍🏻 

This is very helpful as if the original files get deleted and the newly created file will exist then the original contributor will not get the credit as we are using files to fetch contributors.

Thanks a lot 🤗 

---

This PR will be merged shortly

**Comment by hi-Kartik2004** [comment]
Hi @harshraj8843,
Can you test it out and let me know if it's meeting the requirement? Glad to contribute :)

**Comment by harshraj8843** [comment]
@hi-Kartik2004 will test ASAP 👍🏻

**Comment by harshraj8843** [comment]
Works perfectly 👍🏻

**Pull request closed without merging**
