### PR TITLE
[Closed] Hello world

### LINKED ISSUE #3: Write a C program to print hello world
### Description

Write a C program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.c` file
- Add `PrintHelloWorld.c` file in `print-hello-world` folder

</details>

### LINKED ISSUE #4: Write a C program to print hello world
### Description

Write a C program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.c` file
- Add `PrintHelloWorld.c` file in `print-hello-world` folder

</details>

### LINKED ISSUE #5: Write a C++ program to print hello world
### Description

Write a C++ program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.cpp` file
- Add `PrintHelloWorld.cpp` file in `print-hello-world` folder

</details>

### LINKED ISSUE #6: Write a C++ program to print hello world
### Description

Write a C++ program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.cpp` file
- Add `PrintHelloWorld.cpp` file in `print-hello-world` folder

</details>

### LINKED ISSUE #10: Write a JavaScript program to print hello world
### Description

Write a JavaScript program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.js` file
- Add `PrintHelloWorld.js` file in `print-hello-world` folder

</details>

### LINKED ISSUE #11: Write a JavaScript program to print hello world
### Description

Write a JavaScript program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.js` file
- Add `PrintHelloWorld.js` file in `print-hello-world` folder

</details>

### PR DESCRIPTION
**Pull request by KaptainCS3**
### Why:

Closes codinasion/codinasion#4 
Closes codinasion/codinasion#6 
Closes codinasion/codinasion#11

### CODE REVIEW

**Comment by KaptainCS3** [comment]
Hello world task C, C++ and JS done

**Comment by harshraj8843** [comment]
Hey @KaptainCS3 

Please comment `!assign` on 
codinasion/codinasion#4 
codinasion/codinasion#6 
codinasion/codinasion#11 
to prevent any conflict

```
!assign
```

**Comment by KaptainCS3** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @KaptainCS3, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Pull request closed without merging**
