### PR TITLE
Create area-of-triangle.cpp

### LINKED ISSUE #369: Area of Triangle
### Title of article

Write a C++ programme to find area of triangle.

### Additional information

```
a : 10
b : 17
c : 21

s : 24

area : 84
```

s

area*(s-b)*(s-c)})

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by rishav-karanjit**
### Why:

Closes #369

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @rishav-karanjit 

Thanks for contributing to this open source project 😃 

This PR will be reviewed and merged shortly

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by harshraj8843** [comment]
` Preview ` : https://codinasion--pr36-dev-igku8tg2.web.app/programme/area-of-triangle/

<sub>(expires Tue, 29 Mar 2022 08:11:27 GMT)</sub>

**Comment by harshraj8843** [comment]
` LIVE ` : https://codinasion.web.app/programme/area-of-triangle/

**Comment by rishav-karanjit** [comment]
Thank you @harshraj8843

**Pull request merged**
