### PR TITLE
Add sum of cubes python function

### LINKED ISSUE #251: Sum of Cubes
### Title of article

Write a Python programme to find sum of cubes of first n natural numbers.

### Additional information

```
1^3 + 2^3 + 3^3 + ... + n^3
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by johnelbacani**
### Why:

Closes #251 

### What's being changed:

- Added a Python program that prints sum of cubes of first n natural numbers

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by johnelbacani** [comment]
Hi, I'm trying to learn contributing on Github and this is my first attempt. I apologize in advance if I make any big mistakes. Thanks.

**Comment by harshraj8843** [comment]
Hii @johnelbacani 

Thanks for contributing to this open source project 😃 

This PR will be reviewed and merged shortly.

**Comment by harshraj8843** [comment]
> Hi, I'm trying to learn contributing on Github and this is my first attempt. I apologize in advance if I make any big mistakes. Thanks.

We all are here to learn new things 💜

**Comment by harshraj8843** [comment]
` Preview ` : https://codinasion--pr18-dev-5o7hj3iz.web.app/programme/sum-of-cubes/

**Comment by harshraj8843** [comment]
` LIVE ` : https://codinasion.web.app/programme/sum-of-cubes/

**Pull request merged**
