### PR TITLE
440

### LINKED ISSUE #440: Perimeter of square
### Title of article

Write a C programme to find perimeter of square

### Additional information

> Perimeter of square = 4 * ` side `

```
side : 4

perimeter : 16
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Badboy-16**
### Why:

Closes #440

### What's being changed:

- Added perimeter-of-square.c to calculate perimeter of a square from its side.
- Added README.md

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by Badboy-16** [comment]
:) Thank you @harshraj8843 

Just wondering which indent style is used in this project for C? So that I can incorporate the same in my future contributions.

**Comment by harshraj8843** [comment]
> which indent style is used in this project for C?

2 space indent

**Comment by harshraj8843** [comment]
https://codinasion.web.app/programme/perimeter-of-square/

**Pull request merged**
