### PR TITLE
Nea brance

### LINKED ISSUE #287: Write a Julia program to convert miles to feet
### Description

Write a Julia program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-miles-to-feet.jl` file
- Add `convert-miles-to-feet.jl` file in `convert-miles-to-feet` folder

</details>

### LINKED ISSUE #292: Write a R program to convert miles to feet
### Description

Write a R program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_miles_to_feet.r` file
- Add `convert_miles_to_feet.r` file in `convert-miles-to-feet` folder

</details>

### LINKED ISSUE #294: Write a Rust program to convert miles to feet
### Description

Write a Rust program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_miles_to_feet.rs` file
- Add `convert_miles_to_feet.rs` file in `convert-miles-to-feet` folder

</details>

### LINKED ISSUE #340: Write a Julia program to convert miles to feet
### Description

Write a Julia program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-miles-to-feet.jl` file
- Add `convert-miles-to-feet.jl` file in `convert-miles-to-feet` folder

</details>

### LINKED ISSUE #345: Write a R program to convert miles to feet
### Description

Write a R program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_miles_to_feet.r` file
- Add `convert_miles_to_feet.r` file in `convert-miles-to-feet` folder

</details>

### LINKED ISSUE #347: Write a Rust program to convert miles to feet
### Description

Write a Rust program to convert miles to feet

1 mile = 5280 feet

```
Input  : 5
Output : 26400
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_miles_to_feet.rs` file
- Add `convert_miles_to_feet.rs` file in `convert-miles-to-feet` folder

</details>

### LINKED ISSUE #2360: Write a TypeScript program to find the eigenvectors of a matrix
### Description

Write a TypeScript program to find the eigenvectors of a matrix

The eigenvalues and eigenvectors of a linear transformation are the values and vectors that determine the transformation. The eigenvectors of a matrix A are the vectors v for which the matrix equation Av = λv has a non-trivial solution.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
[[-0.23197068724628608, -0.7858302387246789, 0.4082482904638631],
 [-0.5253220933012334, -0.08675134095039447, -0.8164965809277261],
 [-0.8186734993561807, 0.6123275568238899, 0.4082482904638631]]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheEigenvectorsOfAMatrix.ts` file
- Add `FindTheEigenvectorsOfAMatrix.ts` file in `find-the-eigenvectors-of-a-matrix` folder

</details>

### LINKED ISSUE #3189: Write a TypeScript program to find the eigenvectors of a matrix
### Description

Write a TypeScript program to find the eigenvectors of a matrix

The eigenvalues and eigenvectors of a linear transformation are the values and vectors that determine the transformation. The eigenvectors of a matrix A are the vectors v for which the matrix equation Av = λv has a non-trivial solution.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
[[-0.23197068724628608, -0.7858302387246789, 0.4082482904638631],
 [-0.5253220933012334, -0.08675134095039447, -0.8164965809277261],
 [-0.8186734993561807, 0.6123275568238899, 0.4082482904638631]]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheEigenvectorsOfAMatrix.ts` file
- Add `FindTheEigenvectorsOfAMatrix.ts` file in `find-the-eigenvectors-of-a-matrix` folder

</details>

### LINKED ISSUE #3956: Write a Julia program to calculate simple interest
### Description

Write a Julia program to calculate simple interest

Simple interest = (principal amount * rate of interest * time) / 100

```
Principal : 1000
Rate      : 10
Time      : 5

Simple interest : 500
```
<details>
<summary>How to contribute</summary>

- Save the solution in `calculate-simple-interest.jl` file
- Add `calculate-simple-interest.jl` file in `program/calculate-simple-interest` folder

</details>

### LINKED ISSUE #5303: Write a Julia program to calculate simple interest
### Description

Write a Julia program to calculate simple interest

Simple interest = (principal amount * rate of interest * time) / 100

```
Principal : 1000
Rate      : 10
Time      : 5

Simple interest : 500
```
<details>
<summary>How to contribute</summary>

- Save the solution in `calculate-simple-interest.jl` file
- Add `calculate-simple-interest.jl` file in `program/calculate-simple-interest` folder

</details>

### PR DESCRIPTION
**Pull request by Ishay1997**
### Why:

Closes codinasion/codinasion#3956
Closes codinasion/codinasion#287
Closes codinasion/codinasion#292
Closes codinasion/codinasion#294
Closes codinasion/codinasion#2360

### CODE REVIEW

**Comment by Ishay1997** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Ishay1997, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by victoriacheng15** [comment]
@Ishay1997 Please add issue numbers

```
Closes #0000
Closes codinasion/codinasion#2
.
.
. so on
```

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Pull request merged**
