### PR TITLE
Create ConvertStringToConsonantcase.java

### LINKED ISSUE #3807: Write a Java program to convert string to consonantcase
### Description

Write a Java program to convert string to consonantcase

Consonantcase is a style of writing in which all consonants are converted to uppercase and all vowels are converted to lowercase.

```
Input  : "hello world"
Output : "HeLLo WoRLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertStringToConsonantcase.java` file
- Add `ConvertStringToConsonantcase.java` file in `program/convert-string-to-consonantcase` folder

</details>

### LINKED ISSUE #5150: Write a Java program to convert string to consonantcase
### Description

Write a Java program to convert string to consonantcase

Consonantcase is a style of writing in which all consonants are converted to uppercase and all vowels are converted to lowercase.

```
Input  : "hello world"
Output : "HeLLo WoRLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertStringToConsonantcase.java` file
- Add `ConvertStringToConsonantcase.java` file in `program/convert-string-to-consonantcase` folder

</details>

### PR DESCRIPTION
**Pull request by NoyHanan**
### Why:

Closes codinasion/codinasion#3807

### CODE REVIEW

**Review by anandfresh — DISMISSED** [review]
@NoyHanan  Please add the issue id to this PR

**Comment by NoyHanan** [comment]
@anandfresh Hi, how do I do that? :)

**Comment by harshraj8843** [comment]
> @anandfresh Hi, how do I do that? :)

Hey @NoyHanan 

You can add `Closes #ISSUE_NUMBER` in the description of the PR(s)

For this case `Closes codinasion/codinasion#3807`

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Pull request merged**
