### PR TITLE
Create solution.c

### LINKED ISSUE #59: Rupee to Paise
### Title of article

Write a C programme to convert rupee to paise.

### Additional information

```
Input:  15.95
Output: 1595
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by luiscff**
### Why:

Closes #59

### Check off the following:

- [X] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by luiscff** [comment]
This is my first ever pull request so if there is anything that I should/shouldn't do please tell me

**Comment by harshraj8843** [comment]
Hey @luiscff 

Thanks for contributing to this open source project 😃 

This PR will be reviewed and merged shortly.

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by harshraj8843** [comment]
> This is my first ever pull request so if there is anything that I should/shouldn't do please tell me

Hey @luiscff 

This PR is overall good 👍🏻 

Few things you can improve for your next PR are :- 

1. We use `<CodeBlock />` only once, so if you add some code, please consider increasing `repeat` value and update `languages` with `,`

	For example,
	- Before
	  ```js
	  <CodeBlock slots="heading, code" repeat="1" languages="Python" />
	  ```
	- After
	  ```js
	  <CodeBlock slots="heading, code" repeat="2" languages="Python, C" />
	  ```

	[Please see this updated file](https://github.com/luiscff/codinasion/blob/master/programme/rupee-to-paise/README.md) ⬅️ 

	> **Note** : This is applicable to `codinasion/codinasion` repository only

2. You can add `runtime` labels to help users understand your programme better, like adding `Enter rupees`, `Input`, `output`, etc.

**Comment by harshraj8843** [comment]
` Preview ` : https://codinasion--pr28-dev-490i3dd2.web.app/programme/rupee-to-paise/

<sub>(expires Thu, 10 Mar 2022 03:48:47 GMT)</sub>

**Comment by harshraj8843** [comment]
` LIVE ` : https://codinasion.web.app/programme/rupee-to-paise/

**Pull request merged**
