### PR TITLE
C program to find maximum of n numbers

### LINKED ISSUE #674: Write a C program to find maximum of n numbers
### Description

Write a C program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindMaximumOfNNumbers.c` file
- Add `FindMaximumOfNNumbers.c` file in `find-maximum-of-n-numbers` folder

</details>

### PR DESCRIPTION
**Pull request by Zeuhz-Droid**
### Why:

Closes codinasion/codinasion#559

### CODE REVIEW

**Comment by harshraj8843** [comment]
- Please update the file names (the `How to contribute` dropdown in respective issues)

- Please link all the related issue

**Comment by Zeuhz-Droid** [comment]
Done

**Review by victoriacheng15 — DISMISSED** [review]
JS - it is not following the naming convention. Please refer to the `how to contribute` dropdown.

C - the linked issue is not correct. Please link the correct one.

Thank you!

**Comment by Zeuhz-Droid** [comment]
Done.

**Comment by victoriacheng15** [comment]
@Zeuhz-Droid 

The JS program is already in the master branch. Please remove the JS file.

Thank you!

**Comment by Zeuhz-Droid** [comment]
Done.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
