### PR TITLE
Seraph branch

### PR DESCRIPTION
**Pull request by seraph776**
### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hii @seraph776 

Thanks for contributing to this open source project 😃 

This PR will be reviewed and merged shortly.

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Hey @seraph776 

It seems like a test file not the actual programme.

Could you please update it.

**Comment by seraph776** [comment]
I separated the unittest from the function file. Let me know if there is anything else I can do - Thanks!

**Review by harshraj8843 — COMMENTED** [review]
👍🏻

**Review by harshraj8843 — APPROVED** [review]

**Pull request closed without merging**
