### PR TITLE
add ts file to return the power of a number by recursion

### LINKED ISSUE #550: Write a TypeScript program to find power of a number by recursion
### Description

Write a TypeScript program to find power of a number by recursion

Power of a number is calculated by multiplying the number by itself for the given number of times. For example, 2^3 = 2 * 2 * 2 = 8.

Power of a number can be calculated by recursion. The formula is:

```math
x^n = x * x^{n-1}
```

```
Input  : 2 3
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindPowerOfANumberByRecursion.ts` file
- Add `FindPowerOfANumberByRecursion.ts` file in `find-power-of-a-number-by-recursion` folder

</details>

### PR DESCRIPTION
**Pull request by anastazir**
### Why:

Closes codinasion/codinasion#457 

### What's being changed:
added ts file to return the power of a number by recursion

### CODE REVIEW

**Comment by anastazir** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anastazir, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
> !assign

Hey @anastazir 

Comment `!assign` on codinasion/codinasion#457 

```
!assign
```

**Review by victoriacheng15 — APPROVED** [review]
Looks good!

Thank you for contributing! 👍

**Pull request merged**
