### PR TITLE
[Closed] maximum of n numbers code added

### LINKED ISSUE #686: Write a Python program to find maximum of n numbers
### Description

Write a Python program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-maximum-of-n-numbers.py` file
- Add `find-maximum-of-n-numbers.py` file in `find-maximum-of-n-numbers` folder

</details>

### PR DESCRIPTION
**Pull request by RachitGarg-12**
### Why:

Closes codinasion/codinasion#571 

### What's being changed:
I have written the program to find a maximum number in a list of numbers given.
I have added it in the program folder.

### CODE REVIEW

**Comment by RachitGarg-12** [comment]
I have done the work needed in this issue . Can you please review the PR.

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Please update filename to `find-maximum-of-n-numbers.py`

For more detail see `How to contribute` dropdown on respective issues

**Review by victoriacheng15 — APPROVED** [review]
Looks good!

Thank you for contributing! 👍

**Comment by victoriacheng15** [comment]
@RachitGarg-12 

You need to move the file to `find-maximum-of-n-numbers` folder. 

Thank you!

**Pull request closed without merging**
