### PR TITLE
Added files for string length

### LINKED ISSUE #456: Length of string
### Title of article

Write a Java programme to find the length of string.

### Additional information

```
Input  : abcd
Output : 4
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by srabhishekh**
### Why:

Closes #456 

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @srabhishekh 

Thanks for contributing to this project 😃 

This PR will be reviewed and merged shortly

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Hey @srabhishekh 

Please move these files from `programme/string-length` to `programme/length-of-string` folder

If `programme/length-of-string` is not available in your fork, kindly please update the fork or create a folder `programme/length-of-string`

👍🏻

**Comment by srabhishekh** [comment]
hi @harshraj8843,

Thank you for your review comments. I have modified the folder structure.

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by harshraj8843** [comment]
https://codinasion.web.app/programme/length-of-string/

**Pull request merged**
