### PR TITLE
Average of number recursion

### LINKED ISSUE #5380: Write a TypeScript program to find average of digits of a number by recursion
### Description

Write a TypeScript program to find average of digits of a number by recursion

Average of digits of a number is the sum of digits of the number divided by the number of digits in the number. For example, the average of digits of 123 is 6. The sum of digits of 123 is 6 and the number of digits in 123 is 3. So, the average of digits of 123 is 6/3 = 2.

```
Input  : 123
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAverageOfDigitsOfANumberByRecursion.ts` file
- Add `FindAverageOfDigitsOfANumberByRecursion.ts` file in `program/find-average-of-digits-of-a-number-by-recursion` folder

</details>

### PR DESCRIPTION
**Pull request by anandfresh**
### Why:

Closes codinasion/codinasion#4030

### CODE REVIEW

**Review by hi-Kartik2004 — APPROVED** [review]

**Review by hi-Kartik2004 — CHANGES_REQUESTED** [review]
The problem is already solved.

**Comment by hi-Kartik2004** [comment]
Hi Anand! There already exists a typescript file which solves the same problem.

**Comment by anandfresh** [comment]
> Hi Anand! There already exists a typescript file which solves the same problem.

@hi-Kartik2004 there is no typescript file exists in this folder . If it exists , then the file changed will not show as new .

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Pull request merged**
