### PR TITLE
added ConvertStringToDotcase.js file

### LINKED ISSUE #2431: Write a JavaScript program to convert string to dotcase
### Description

Write a JavaScript program to convert string to dotcase

Dotcase is a style of writing in which all letters are lowercase and spaces are replaced with periods.

```
Input  : "hello world"
Output : "hello.world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToDotcase.js` file
- Add `ConvertStringToDotcase.js` file in `convert-string-to-dotcase` folder

</details>

### PR DESCRIPTION
**Pull request by CodingWithHardik**
### Why:

Closes codinasion/codinasion#1795

### CODE REVIEW

**Review by victoriacheng15 — COMMENTED** [review]
um, `kebabCase` or `dotCase`?

**Comment by CodingWithHardik** [comment]
> um, `kebabCase` or `dotCase`?

dotCase I have done correctly

**Comment by CodingWithHardik** [comment]
> um, `kebabCase` or `dotCase`?

Idk you are confuse

**Comment by CodingWithHardik** [comment]
> um, `kebabCase` or `dotCase`?

Ohk now i got how you got confused i made a pull request of js file in kebabCase and dotCase both kebabCase is already merged and in this you are confused

**Comment by CodingWithHardik** [comment]
> > > um, `kebabCase` or `dotCase`?
> > 
> > 
> > Ohk now i got how you got confused i made a pull request of js file in kebabCase and dotCase both kebabCase is already merged and in this you are confused
> 
> The file name said `dotCase` while the function named `kebabCase`.

Ohk i was thinking that result was giving in dotcase but i didn't saw the function name soory 🥲

**Comment by CodingWithHardik** [comment]
> > > > um, `kebabCase` or `dotCase`?
> > > 
> > > 
> > > Ohk now i got how you got confused i made a pull request of js file in kebabCase and dotCase both kebabCase is already merged and in this you are confused
> > 
> > 
> > The file name said `dotCase` while the function named `kebabCase`.
> 
> Ohk i was thinking that result was giving in dotcase but i didn't saw the function name soory 🥲

I fixed it

**Review by victoriacheng15 — APPROVED** [review]
Looks good!

Thank you for contributing!

**Pull request merged**
