### PR TITLE
Check Palindrome numbers in Perl Language

### LINKED ISSUE #1993: Write a Perl program to check palindrome number
### Description

Write a Perl program to check palindrome number

Palindrome numbers are the numbers for which reverse is exactly same as the original number. For example, 121 is palindrome, but 123 is not palindrome.

```
Input  : 121
Output : Palindrome Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check_palindrome_number.pl` file
- Add `check_palindrome_number.pl` file in `check-palindrome-number` folder

</details>

### PR DESCRIPTION
**Pull request by gupta-soham**
### Why:

Closes codinasion/codinasion#1576 

### What's being changed:
Added Perl script to find palindromic numbers.

### CODE REVIEW

**Comment by gupta-soham** [comment]
Can the owner or reviewers please merge my PR as this branch is getting out of date @victoriacheng15 @PrajwalBorkar, Thanks.

**Comment by victoriacheng15** [comment]
@gupta-soham we are reviewing PRs based on queue base. Please be patient. Thank you!

**Review by harshraj8843 — COMMENTED** [review]
Thanks for contributing 👍🏻

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
