### PR TITLE
wrote program to divide two numbers in golang

### LINKED ISSUE #94: Write a GO program to divide two numbers
### Description

Write a GO program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `divide_two_numbers.go` file
- Add `divide_two_numbers.go` file in `divide-two-numbers` folder

</details>

### LINKED ISSUE #111: Write a GO program to divide two numbers
### Description

Write a GO program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `divide_two_numbers.go` file
- Add `divide_two_numbers.go` file in `divide-two-numbers` folder

</details>

### PR DESCRIPTION
**Pull request by renanlmiranda**
### Why:

Closes codinasion/codinasion#94 

### What's being changed:
Wrote a program in golang to divide two numbers

### CODE REVIEW

**Comment by renanlmiranda** [comment]
Done, I changed the name to the right one too, I hadn't seen it! Thanks

**Comment by harshraj8843** [comment]
Hey @renanlmiranda 

Please comment on codinasion/codinasion#94 , to be auto-assigned to the linked issue (to prevent any conflict)

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Comment by renanlmiranda** [comment]
@harshraj8843  Okay, I commented on codinasion/codinasion#94

**Pull request merged**
