### PR TITLE
[Closed] update code owners

### PR DESCRIPTION
**Pull request by anandfresh**
### Why:

Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by anandfresh** [comment]
reopen

**Comment by harshraj8843** [comment]
Hey @anandfresh 

Could you please state the reason behind this PR?

**Comment by anandfresh** [comment]
> Hey @anandfresh
> 
> Could you please state the reason behind this PR?

Hi @harshraj8843  , I would like to be a reviewer for this program repository .

**Comment by harshraj8843** [comment]
> No need to reopen this issue

Now you are a member of the @codinasion/program team, which will give you access to review or maintain this repo 👍🏻 

Thanks for joining us 🤗

**Pull request closed without merging**
