### PR TITLE
[Closed] feat: convert inches to centimeters with TS

### LINKED ISSUE #667: Write a TypeScript program to convert inches to centimeters
### Description

Write a TypeScript program to convert inches to centimeters

1 inch = 2.54 centimeters

```
Input  : 5
Output : 12.7
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToCentimeters.ts` file
- Add `ConvertInchesToCentimeters.ts` file in `convert-inches-to-centimeters` folder

</details>

### PR DESCRIPTION
**Pull request by MaestroDagan**
### Why:
Closes codinasion/codinasion#557

### What's being changed:
The file ConvertInchesToCentimeters.ts has been added.

### CODE REVIEW

**Review by victoriacheng15 — COMMENTED** [review]
umm, looks good, but I am wondering if @harshraj8843 would like to see it in function style or not?

**Comment by MaestroDagan** [comment]
> umm, looks good, but I am wondering if @harshraj8843 would like to see it in function style or not?

Well, I could make it in function style, makes sense.
I'll just do it, then it's not so hardcoded.
Thanks for reviewing!

**Comment by MaestroDagan** [comment]
did it!

**Review by victoriacheng15 — APPROVED** [review]
Thank you for making the change and contributing as well! 👍

**Pull request closed without merging**
