### PR TITLE
added hello world in swift language

### LINKED ISSUE #20: Write a Swift program to print hello world
### Description

Write a Swift program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.swift` file
- Add `PrintHelloWorld.swift` file in `print-hello-world` folder

</details>

### LINKED ISSUE #21: Write a Swift program to print hello world
### Description

Write a Swift program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.swift` file
- Add `PrintHelloWorld.swift` file in `print-hello-world` folder

</details>

### PR DESCRIPTION
**Pull request by renanlmiranda**
### Why:

Closes codinasion/codinasion#21 

### What's being changed:
Print Hello World in swift language

### CODE REVIEW

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Hey @renanlmiranda 

Please follow the naming convention from `how to contribue` dropdown in the issue.  Otherwise, the code looks good!

Thank you for contributing! 👍

**Comment by renanlmiranda** [comment]
Ok, no problem! Thanks

**Comment by renanlmiranda** [comment]
Done, i change the file name !Thanks

**Review by victoriacheng15 — APPROVED** [review]

**Comment by harshraj8843** [comment]
Hey @renanlmiranda 

Please comment `!assign` on codinasion/codinasion#21 to be auto-assigned to the linked issue (to prevent any conflict)

```
!assign
```

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Comment by renanlmiranda** [comment]
@harshraj8843 Okay, I commented on codinasion/codinasion#21

**Pull request merged**
