### PR TITLE
Reverse an array js and find smallest number in matrix ts

### LINKED ISSUE #4959: Write a JavaScript program to reverse an array
### Description

Write a JavaScript program to reverse an array

```
Input  : [1, 2, 3, 4, 5]
Output : [5, 4, 3, 2, 1]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ReverseAnArray.js` file
- Add `ReverseAnArray.js` file in `program/reverse-an-array` folder

</details>

### LINKED ISSUE #5141: Write a TypeScript program to find smallest element in a matrix
### Description

Write a TypeScript program to find smallest element in a matrix

```
Input :
4 7 3
9 4 2
0 6 4

Output : 0
```

<sub>Contributed by - @ShubhraSuman</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSmallestElementInAMatrix.ts` file
- Add `FindSmallestElementInAMatrix.ts` file in `program/find-smallest-element-in-a-matrix` folder

</details>

### PR DESCRIPTION
**Pull request by Sdfeagt**
### Why:
Added a JS solution to reversing an array and added a TS solution to finding smallest number in a matrix
Closes codinasion/codinasion#3618 
Closes codinasion/codinasion#3798

### What's being changed:
Added 2 files with solutions

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
Can you pls add the Issue ID for FindSmallestElementInAMatrix

**Comment by Sdfeagt** [comment]
@anandfresh This PR is linked to an issue with reversing an array. Why do you want me to add issue ID for FindSmallestElementInAMatrix?

**Comment by anandfresh** [comment]
> @anandfresh This PR is linked to an issue with reversing an array. Why do you want me to add issue ID for FindSmallestElementInAMatrix?

@Sdfeagt  This PR has two file changes  ( Array reverse and FindSmallestElementInAMatrix ), where in you have added issue ID only for array reverse and not for FindSmallestElementInAMatrix.
Can you pls check properly and make sure you are adding issue id's for all the changes

**Review by anandfresh — APPROVED** [review]

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
