### PR TITLE
Cuboid volume

### LINKED ISSUE #69: Write a C program to find volume of a cuboid
### Description

Write a C program to find volume of a cuboid

Volume of a cuboid = `Length` × `Width` × `Height`

```
Length : 2
Width  : 3
Height : 4

Volume : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACuboid.c` file
- Add `FindVolumeOfACuboid.c` file in `find-volume-of-a-cuboid` folder

</details>

### LINKED ISSUE #71: Write a C++ program to find volume of a cuboid
### Description

Write a C++ program to find volume of a cuboid

Volume of a cuboid = `Length` × `Width` × `Height`

```
Length : 2
Width  : 3
Height : 4

Volume : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACuboid.cpp` file
- Add `FindVolumeOfACuboid.cpp` file in `find-volume-of-a-cuboid` folder

</details>

### LINKED ISSUE #86: Write a C program to find volume of a cuboid
### Description

Write a C program to find volume of a cuboid

Volume of a cuboid = `Length` × `Width` × `Height`

```
Length : 2
Width  : 3
Height : 4

Volume : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACuboid.c` file
- Add `FindVolumeOfACuboid.c` file in `find-volume-of-a-cuboid` folder

</details>

### LINKED ISSUE #88: Write a C++ program to find volume of a cuboid
### Description

Write a C++ program to find volume of a cuboid

Volume of a cuboid = `Length` × `Width` × `Height`

```
Length : 2
Width  : 3
Height : 4

Volume : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACuboid.cpp` file
- Add `FindVolumeOfACuboid.cpp` file in `find-volume-of-a-cuboid` folder

</details>

### PR DESCRIPTION
**Pull request by KaptainCS3**
### Why:

Closes codinasion/codinasion#69 
Closes codinasion/codinasion#71

### CODE REVIEW

**Comment by KaptainCS3** [comment]
cuboid program C and C++ done

**Comment by harshraj8843** [comment]
Hey @KaptainCS3 

Please comment `!assign` on codinasion/codinasion#69 codinasion/codinasion#71 , to prevent any conflict

```
!assign
```

**Comment by KaptainCS3** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @KaptainCS3, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Please follow the name convention as the issue mentioned. They should be `FindVolumeOfACuboid.c` and `FindVolumeOfACuboid.cpp`

Also, I saw error for c++ function

image


Thank you, for contributing! :D

**Comment by KaptainCS3** [comment]
update naming conversion and change function return type.

**Comment by KaptainCS3** [comment]
print hello world program done waiting on your review

**Review by victoriacheng15 — APPROVED** [review]
Thank you for the changes! :D

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
