### PR TITLE
Print pattern 1

### PR DESCRIPTION
**Pull request by yacine-zitouni**
### Why:

Closes [#96](https://github.com/codinasion/codinasion/issues/96)

### What's being changed:

- Added a Python program that prints the given pattern 

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hii @yacine-zitouni 

Thanks for contributing to this open source project 😃 

This PR will be reviewed and merged shortly.

**Review by harshraj8843 — APPROVED** [review]

**Review by harshraj8843 — APPROVED** [review]

**Comment by yacine-zitouni** [comment]
Hi, @harshraj8843, I'm new to github, should i create a new branch to every issue ? thank you.

**Comment by harshraj8843** [comment]
> should i create a new branch to every issue ?

Yes, you should create a new branch for every new PR.

#### Benefits :- 
- Easier to review pull request
- clean commit history
- easy to add new commits in PR

Thanks 😃

**Comment by harshraj8843** [comment]
@yacine-zitouni no need to worry about all commits in this PR

**Comment by harshraj8843** [comment]
` LIVE ` : https://codinasion.web.app/programme/pattern-1/

` LIVE ` : https://codinasion.web.app/programme/pattern-2/

**Pull request merged**
