### PR TITLE
 addTwoMatrices

### LINKED ISSUE #3454: Write a TypeScript program to add two matrices
### Description

Write a TypeScript program to add two matrices

Matrix addition is the process of adding two matrices by adding the corresponding elements of the two matrices. Two matrices must have an equal number of rows and columns to be added.

```
Input  :
1 2 3
4 5 6
7 8 9

1 2 3
4 5 6
7 8 9

Output :
2 4 6
8 10 12
14 16 18
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/AddTwoMatrices.ts` file
- Add `AddTwoMatrices.ts` file in `add-two-matrices` folder

</details>

### LINKED ISSUE #4564: Write a TypeScript program to add two matrices
### Description

Write a TypeScript program to add two matrices

Matrix addition is the process of adding two matrices by adding the corresponding elements of the two matrices. Two matrices must have an equal number of rows and columns to be added.

```
Input  :
1 2 3
4 5 6
7 8 9

1 2 3
4 5 6
7 8 9

Output :
2 4 6
8 10 12
14 16 18
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/AddTwoMatrices.ts` file
- Add `AddTwoMatrices.ts` file in `add-two-matrices` folder

</details>

### PR DESCRIPTION
**Pull request by weaam88**
Why:

Closes codinasion/codinasion#3454

What's being changed: added implementation in type script to addTwoMatrices

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
@weaam88  please add the issue it to this PR

**Comment by weaam88** [comment]
> @weaam88 please add the issue it to this PR

did i did it write?

**Comment by anandfresh** [comment]
> > @weaam88 please add the issue it to this PR
> 
> did i did it write?

No , you have to add the issue in under Why with Closes keyword.
Refer the below PR for example : https://github.com/codinasion/program/pull/6171 

While creating PR , you have everything including the Closes keyowrd , only thing you need to add is the issues id in the place holder

**Comment by weaam88** [comment]
> > > @weaam88 please add the issue it to this PR
> > 
> > 
> > did i did it write?
> 
> No , you have to add the issue in under Why with Closes keyword. Refer the below PR for example : codinasion/program#6171
> 
> While creating PR , you have everything including the Closes keyowrd , only thing you need to add is the issues id in the place holder

ok, done

**Comment by anandfresh** [comment]
> > > > @weaam88 please add the issue it to this PR
> > > 
> > > 
> > > did i did it write?
> > 
> > 
> > No , you have to add the issue in under Why with Closes keyword. Refer the below PR for example : codinasion/program#6171
> > While creating PR , you have everything including the Closes keyowrd , only thing you need to add is the issues id in the place holder
> 
> ok, done

@weaam88  You have added the PR ID , but you should add the issue ID.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Pull request merged**
