### PR TITLE
Lcm recursion

### LINKED ISSUE #412: Write a Java program to find lcm of two numbers by recursion
### Description

Write a Java program to find lcm of two numbers by recursion

LCM (Least Common Multiple) of two numbers is the smallest number that can be divided by both numbers. For example, the LCM of 15 and 20 is 60 and LCM of 10 and 15 is 30.

```
Input  : 12 18
Output : 36
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindLcmOfTwoNumbersByRecursion.java` file
- Add `FindLcmOfTwoNumbersByRecursion.java` file in `find-lcm-of-two-numbers-by-recursion` folder

</details>

### PR DESCRIPTION
**Pull request by sahooankeeta**
### Why:

Closes codinasion/codinasion#345

### What's being changed:
Added lcm of 2 numbers by recursion java

### CODE REVIEW

**Comment by victoriacheng15** [comment]
Please link all related issues for this.

Example:
```
Closes codinasion/codinasion#2
Closes codinasion/codinasion#3
Closes codinasion/codinasion#4
```

Thank you!

**Comment by sahooankeeta** [comment]
Closes codinasion/codinasion#345
Closes codinasion/codinasion#545
Closes codinasion/codinasion#846

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
**FindLcmOfTwoNumbersByRecursion:**

The function didn't show correct output.  With 15 and 20, the output should be 60, but I got 20 instead.

image


Thank you!

**Comment by sahooankeeta** [comment]
I executed 15 and 20 and this is my output screenshot. 
lcm

**Review by victoriacheng15 — APPROVED** [review]

**Comment by victoriacheng15** [comment]
> I executed 15 and 20 and this is my output screenshot. lcm

I just checked again and you are right. It was my bad. 

Thank you for contributing! 👍

**Pull request merged**
