### PR TITLE
added swift file

### LINKED ISSUE #126: Write a Swift program to find cube of a number
### Description

Write a Swift program to find cube of a number

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindCubeOfANumber.swift` file
- Add `FindCubeOfANumber.swift` file in `find-cube-of-a-number` folder

</details>

### LINKED ISSUE #143: Write a Swift program to find cube of a number
### Description

Write a Swift program to find cube of a number

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindCubeOfANumber.swift` file
- Add `FindCubeOfANumber.swift` file in `find-cube-of-a-number` folder

</details>

### PR DESCRIPTION
**Pull request by toddmcintire**
### Why:
created swift file that cubes given input.

Closes  codinasion/codinasion#126

### What's being changed:
created find-cube-of-a-number.swift

### CODE REVIEW

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Hi @toddmcintire!

Please follow the naming convention (this is located in the `how to contribute` from the issue 143) for swift.

Thank you for your contributing!!! :D

**Comment by toddmcintire** [comment]
> Hi @toddmcintire!
> 
> Please follow the naming convention (this is located in the `how to contribute` from the issue 143) for swift.
> 
> Thank you for your contributing!!! :D

Oops my mistake, I did not see that dropdown. Should hopefully have the correct name now.

**Review by victoriacheng15 — APPROVED** [review]
Looks good! Thank you for making the change! 👍

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
