### PR TITLE
created ConvertStringToConsonantcase.cpp

### LINKED ISSUE #5145: Write a C++ program to convert string to consonantcase
### Description

Write a C++ program to convert string to consonantcase

Consonantcase is a style of writing in which all consonants are converted to uppercase and all vowels are converted to lowercase.

```
Input  : "hello world"
Output : "HeLLo WoRLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertStringToConsonantcase.cpp` file
- Add `ConvertStringToConsonantcase.cpp` file in `program/convert-string-to-consonantcase` folder

</details>

### PR DESCRIPTION
**Pull request by shekaushik**
Closes codinasion/codinasion#3802

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
@shekaushik Please make sure to add the issue number in the PR

**Review by anandfresh — CHANGES_REQUESTED** [review]
@shekaushik  , Can you please add the issue id ( The original issue id reported in the - https://github.com/codinasion/program/issues ) . 
But you have attached your PR ID

**Comment by shekaushik** [comment]
Sorry. I'm very confused..what is issue number?

**Review by anandfresh — APPROVED** [review]
@shekaushik  You have given the PR ID , but you have to attach the issue ID from

**Pull request merged**
