### PR TITLE
Area of circle

### LINKED ISSUE #704: Write a Dart program to find area of a circle
### Description

Write a Dart program to find area of a circle

Area of circle = π × `Radius`^2

```
Radius : 2

Area : 12.566370614359172
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find_area_of_a_circle.dart` file
- Add `find_area_of_a_circle.dart` file in `find-area-of-a-circle` folder

</details>

### PR DESCRIPTION
**Pull request by anandfresh**
### Why:

Closes codinasion/codinasion#583

### CODE REVIEW

**Review by PraaneshSelvaraj — DISMISSED** [review]
You Gave two solutions but only issue was added in the comment

**Comment by anandfresh** [comment]
> You Gave two solutions but only issue was added in the comment

@PraaneshSelvaraj  Its one issue only .

**Comment by PraaneshSelvaraj** [comment]
@anandfresh It has an error.
image

**Comment by anandfresh** [comment]
> @anandfresh It has an error. image

@PraaneshSelvaraj  pls retest now

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

Screenshot from 2023-04-27 14-26-33

**Pull request merged**
