### PR TITLE
[Closed] Create MiletoKm.java

### LINKED ISSUE #886: Write a Java program to convert miles to kilometers
### Description

Write a Java program to convert miles to kilometers

1 mile = 1.609 kilometers

```
Input  : 5
Output : 8.04672
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToKilometers.java` file
- Add `ConvertMilesToKilometers.java` file in `convert-miles-to-kilometers` folder

</details>

### LINKED ISSUE #1109: Write a Java program to convert miles to kilometers
### Description

Write a Java program to convert miles to kilometers

1 mile = 1.609 kilometers

```
Input  : 5
Output : 8.04672
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMilesToKilometers.java` file
- Add `ConvertMilesToKilometers.java` file in `convert-miles-to-kilometers` folder

</details>

### PR DESCRIPTION
**Pull request by asubodh**
### Why:

Closes codinasion/codinasion#886

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@asubodh 

Please link the issue

Example:
`Closes codinasion/codinasion#2`

Thank you!

**Comment by asubodh** [comment]
All the issues are fixed @victoriacheng15

**Comment by victoriacheng15** [comment]
> All the issues are fixed @victoriacheng15

When you open this PR, the template asks you to `link issue number` and explain `What's being changed`, but you didn't link the issue number. I am asking you to link the issue for this.

Thank you!

**Comment by harshraj8843** [comment]
Issue codinasion/codinasion#886 already closed

**Pull request closed without merging**
