### PR TITLE
Kotlin program to find the average of all numbers in an array #4908

### LINKED ISSUE #3578: Write a Kotlin program to find the average of all numbers in an array
### Description

Write a Kotlin program to find the average of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheAverageOfAllNumbersInAnArray.kt` file
- Add `FindTheAverageOfAllNumbersInAnArray.kt` file in `find-the-average-of-all-numbers-in-an-array` folder

</details>

### LINKED ISSUE #4919: Write a Kotlin program to find the average of all numbers in an array
### Description

Write a Kotlin program to find the average of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindTheAverageOfAllNumbersInAnArray.kt` file
- Add `FindTheAverageOfAllNumbersInAnArray.kt` file in `find-the-average-of-all-numbers-in-an-array` folder

</details>

### PR DESCRIPTION
**Pull request by D-I-J**
Closes codinasion/codinasion#3578

## 📑 Description
A simple Kotlin program that finds average of all number in an array.

  ✅ Checks
- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

Closes # <#4908>

---

### Summary
📝🔢🧮

Added a main function to `FindTheAverageOfAllNumbersInAnArray.kt` that creates and prints the average of an array of integers. The function showcases the usage of the array and the average functions.

> _`main` creates array_
> _sums and divides elements_
> _prints average: fall_

### Walkthrough
*  Add a main function to demonstrate how to find the average of all numbers in an array ([link](https://github.com/codinasion/program/pull/7455/files?diff=unified&w=0#diff-660215ded138340163552404d4cb31a842f4bd00073cbf6265e8045dc7a48737L1-R6))

### CODE REVIEW

**Comment by D-I-J** [comment]
@anandfresh ,@tanishq-singh-2407 help me complete this merge.
If there is any issues please tell me so i can fix them

**Comment by harshraj8843** [comment]
> @anandfresh ,@tanishq-singh-2407 help me complete this merge. If there is any issues please tell me so i can fix them

Hey @D-I-J 

You should link the PRs with the respective issue by using `Closes #ISSUE_NUMBER` in the PR description

For example, `Closes codinasion/codinasion#3578` for this PR

Follow this for your future contributions in any repository 🤗

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Comment by D-I-J** [comment]
@harshraj8843 thanks for approving my contribution and guiding me out.
You are welcome , I am thrilled to contribute to it.

image
you mean this one marked with pen in the image.
 I should write it like this (Closes codinasion/codinasion#3578).

**Comment by harshraj8843** [comment]
Yes, 

`Closes codinasion/codinasion#3578` or 
`Closes https://github.com/codinasion/codinasion/issues/3578`

**Pull request merged**
