### PR TITLE
[Closed] Write a C# program to divide two numbers 

### LINKED ISSUE #90: Write a C# program to divide two numbers
### Description

Write a C# program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.cs` file
- Add `DivideTwoNumbers.cs` file in `divide-two-numbers` folder

</details>

### LINKED ISSUE #107: Write a C# program to divide two numbers
### Description

Write a C# program to divide two numbers

```
Input  : 2 4
Output : 0.5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `DivideTwoNumbers.cs` file
- Add `DivideTwoNumbers.cs` file in `divide-two-numbers` folder

</details>

### PR DESCRIPTION
**Pull request by Zeuhz-Droid**
### Why: Write a C# program to divide two numbers 

Closes codinasion/codinasion#90

### CODE REVIEW

**Comment by victoriacheng15** [comment]
Hey @Zeuhz-Droid 

You are pushing changes from the master branch. Please create a branch and refer to [make changes](https://github.com/codinasion/program/blob/master/CONTRIBUTING.md#make-changes) if needed.

Thank you!

**Comment by Zeuhz-Droid** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Zeuhz-Droid, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Please link all the related issues

for example
`Closes codinasion/codinasion#2`
`Closes codinasion/codinasion#3`
etc...

**Comment by Zeuhz-Droid** [comment]
Done

**Comment by Zeuhz-Droid** [comment]
Done

**Comment by Zeuhz-Droid** [comment]
DOne

**Pull request closed without merging**
