### PR TITLE
Add Compound Interest Calculator Python Function

### LINKED ISSUE #227: Compound Interest Calculator
### Title of article

Write a Python programme to calculate compound interest.

### Additional information

P : Principle Amount
T : Time Period
R : Rate of Interest

A : Amount
CI : Compound Interest

### Programme

```
Enter P : 100
Enter T : 10
Enter R : 10

Amount : 259.37
Compound Interest : 159.37
```

### Formula

```
A = P*((1+(r/100))^t)
```

```
CI = A - P
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by theanorak**
### Why:

Closes #227 

### What's being changed:

Added a python program that prints compound interest based on information input from user.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @theanorak 

Thanks for your continuous contributions 😃 

This PR will be reviewed and merged shortly

**Comment by theanorak** [comment]
Thanks @harshraj8843 😄

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by harshraj8843** [comment]
` Preview ` : https://codinasion--pr18-dev-5o7hj3iz.web.app/programme/compound-interest-calculator/

**Comment by harshraj8843** [comment]
` LIVE ` : https://codinasion.web.app/programme/compound-interest-calculator/

**Pull request merged**
