### PR TITLE
X power Y

### PR DESCRIPTION
**Pull request by harshi1122**
### Why:

Closes https://github.com/codinasion/codinasion/issues/92

### What's being changed:
- Added a Python program to program folder that finds X power Y
### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Please add a `README.md` for `python/programme/5-average-of-numbers/`

**Comment by harshi1122** [comment]
@harshraj8843 
somehow all the readme files added by me are visible here but not in their respective branches

**Comment by harshraj8843** [comment]
Hey @harshi1122 

No worries, overall commit will be same.

#155

**Review by harshraj8843 — APPROVED** [review]

**Comment by harshraj8843** [comment]
` Preview ` : https://codinasion--pr10-dev-65w226w0.web.app/python/programme/7-X-power-Y/

<sub>(expires Sun, 27 Feb 2022 02:52:38 GMT)</sub>

**Comment by harshraj8843** [comment]
` LIVE ` : https://codinasion.web.app/python/programme/7-X-power-Y/

**Pull request merged**
