### PR TITLE
ConvertCentimetersToInches.java

### LINKED ISSUE #3406: Write a Java program to convert centimeters to inches
### Description

Write a Java program to convert centimeters to inches

1 inch = 2.54 centimeters

```
Input  : 12.7
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToInches.java` file
- Add `ConvertCentimetersToInches.java` file in `convert-centimeters-to-inches` folder

</details>

### PR DESCRIPTION
**Pull request by grraghav120**
### Why:

Closes codinasion/codinasion#2516 

### What's being changed:
ConvertCentimetersToInches.java

### CODE REVIEW

**Comment by joao-vitor-souza** [comment]
I tried to run with any float number and it raised `java.util.InputMismatchException`.

**Comment by joao-vitor-souza** [comment]
I tried to run it with any float number and it raised `java.util.InputMismatchException`.

**Comment by Tc2r1** [comment]
@grraghav120 this repo is excluded from hacktoberfest2022, however I have a repo that is not excluded you may be able to contribute to:

shameless self plug: lol its not as fancy as this one but its honestly to help newer developers, lmk:

https://github.com/Tc2r1/DevInterview_Questions

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
