### PR TITLE
Compound interest program done

### PR DESCRIPTION
**Pull request by KaptainCS3**
### Why:

Closes codinasion/codinasion#1060

### CODE REVIEW

**Comment by KaptainCS3** [comment]
task done

**Comment by victoriacheng15** [comment]
Please link the issue number.

Thank you!

**Comment by KaptainCS3** [comment]
compound interest issue codinasion/program#1619 done

**Comment by victoriacheng15** [comment]
> compound interest issue codinasion/program#1619 done

Please follow what the pull request template asks. It specifically asks you to change issue number after the `Closes` word. So you need to update the first comment.

Thank you!

**Comment by KaptainCS3** [comment]
Why:
Closes codinasion/program#1619

What's being changed:

**Comment by victoriacheng15** [comment]
> Why: Closes codinasion/program#1619
> 
> What's being changed:

The number you linked is this pull request. The `issue` number is the issue that you want to close. The first comment is the one that you should add issue number there. And it will link this PR to the issue with the keyword. It will look like `Closes codinasion/codinasion#1060`. This will help us to close the issue once this PR is merged. 

I just edited that for you. Check the first comment. Next time, please follow the instruction from the pull request template.

Thank you.

**Review by victoriacheng15 — APPROVED** [review]
Looks good!

Thank you for contributing!

**Pull request merged**
