### PR TITLE
[Closed] Delete duplicated extensions and rename wrong file names

### PR DESCRIPTION
**Pull request by joao-vitor-souza**
This PR deletes some duplicated files that were found by the `find_duplicate.py` script.

### CODE REVIEW

**Comment by harshraj8843** [comment]
Thanks for this PR 😃 

It is really helpful 👍🏻

**Comment by harshraj8843** [comment]
This PR will be tracked in #4859

**Comment by joao-vitor-souza** [comment]
@harshraj8843, I've merged the files of  `find-volume-of-cube` into `find-volume-of-a-cube`, they had files with the same purpose.

**Comment by harshraj8843** [comment]
This PR is tracked in #4860

**Pull request closed without merging**
