### PR TITLE
Added code to find the square root.

### LINKED ISSUE #3599: Write a Java program to find square root of a number
### Description

Write a Java program to find square root of a number

Square root of a number is the number that when multiplied by itself gives the original number. For example, square root of 4 is 2 because 2 * 2 = 4. Similarly, square root of 9 is 3 because 3 * 3 = 9.

```
Input  : 4
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSquareRootOfANumber.java` file
- Add `FindSquareRootOfANumber.java` file in `find-square-root-of-a-number` folder

</details>

### PR DESCRIPTION
**Pull request by saiprakash255**
Closes codinasion/codinasion#2642

### CODE REVIEW

**Comment by sidharthbh8** [comment]
@saiprakash255 hey how you made two separate pull requests can you tell me Im new to open source and contribution

**Comment by saiprakash255** [comment]
@sidharthbh8 , one request is in java and the other is in GO.

**Comment by sidharthbh8** [comment]
yeah can you tell me how
because when i pushed two PRs they both got into one PR

**Comment by joao-vitor-souza** [comment]
> yeah can you tell me how because when i pushed two PRs they both got into one PR

You have to create two branches, each branch is used to make a PR at a time. @saiprakash255 create two branches, one for the JAVA program, and one for GO, then he pushed from both branches, making 2 PRs.

**Review by joao-vitor-souza — APPROVED** [review]

**Pull request merged**
