### PR TITLE
Adding two numbers program

### PR DESCRIPTION
**Pull request by Mrczarny**
### What's being changed:

Adds program that adds two numbers

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @Mrczarny 

Thanks for your contributions to this project 😃 

This PR isn't `valid`. You modified file in `wrong` folder.

`solution.cs` is already available for [`programme/minimum-of-numbers`](https://github.com/Mrczarny/codinasion/tree/csharp/programme/minimum-of-numbers). Please don't modify it.

Please add your `solution.cs` in [`programme/add-two-numbers/`](https://github.com/Mrczarny/codinasion/tree/csharp/programme/add-two-numbers)

**Comment by harshraj8843** [comment]
Hey @Mrczarny 

Thanks for your contributions to this project 😃 

This PR isn't `valid`. You modified file in `wrong` folder.

`solution.cs` is already available for [`programme/minimum-of-numbers`](https://github.com/Mrczarny/codinasion/tree/csharp/programme/minimum-of-numbers). Please don't modify it.

Please add your `solution.cs` in [`programme/add-two-numbers/`](https://github.com/Mrczarny/codinasion/tree/csharp/programme/add-two-numbers)

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Please add your `solution.cs` in [`programme/add-two-numbers/`](https://github.com/Mrczarny/codinasion/tree/csharp/programme/add-two-numbers)

**Comment by Mrczarny** [comment]
Sorry but way you name files is bit confusing. I sugest renaming them from `solution.*` to `name-of-problem.*`.

**Comment by harshraj8843** [comment]
> Sorry but way you name files is bit confusing. I sugest renaming them from `solution.*` to `name-of-problem.*`.

Thanks for you suggestion, we will work on it asap 👍🏻

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by harshraj8843** [comment]
` Preview ` : https://codinasion--pr32-dev-s0w5cv9u.web.app/programme/add-two-numbers/

<sub>(expires Mon, 14 Mar 2022 03:17:24 GMT)</sub>

**Pull request merged**
