### PR TITLE
added check-armstrong-number.py file

### LINKED ISSUE #1249: Write a Python program to check armstrong number
### Description

Write a Python program to check armstrong number

An Armstrong number is a number that is equal to the sum of cubes of its digits.

```
Input  : 153
Output : Armstrong Number
```
<details>
<summary>How to contribute</summary>

- Save the solution in `check-armstrong-number.py` file
- Add `check-armstrong-number.py` file in `check-armstrong-number` folder

</details>

### PR DESCRIPTION
**Pull request by CodingWithHardik**
Closes codinasion/codinasion#992

### CODE REVIEW

**Comment by victoriacheng15** [comment]
Please link the issue number.

Thank you!

**Comment by CodingWithHardik** [comment]
donw

**Comment by victoriacheng15** [comment]
> done

It should be the language-specific issue. I was not clear on this part. And I went ahead to changed the issue number.

Thank you!

**Review by victoriacheng15 — APPROVED** [review]
Looks good!

Thank you for contributing! 👍

**Pull request merged**
