### PR TITLE
program/check-anagram-string/WriteAProgramToCheckAnagramString.fs

### LINKED ISSUE #3187: Write a F# program to convert days to hours
### Description

Write a F# program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToHours.fs` file
- Add `ConvertDaysToHours.fs` file in `convert-days-to-hours` folder

</details>

### LINKED ISSUE #3208: Write a F# program to convert time from 24-hour to 12-hour format
### Description

Write a F# program to convert time from 24-hour to 12-hour format

```
Input  : 12:05:45
Output : 12:05:45PM
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertTimeFrom24-hourTo12-hourFormat.fs` file
- Add `ConvertTimeFrom24-hourTo12-hourFormat.fs` file in `convert-time-from-24-hour-to-12-hour-format` folder

</details>

### LINKED ISSUE #4270: Write a F# program to convert days to hours
### Description

Write a F# program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertDaysToHours.fs` file
- Add `ConvertDaysToHours.fs` file in `convert-days-to-hours` folder

</details>

### LINKED ISSUE #4291: Write a F# program to convert time from 24-hour to 12-hour format
### Description

Write a F# program to convert time from 24-hour to 12-hour format

```
Input  : 12:05:45
Output : 12:05:45PM
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertTimeFrom24-hourTo12-hourFormat.fs` file
- Add `ConvertTimeFrom24-hourTo12-hourFormat.fs` file in `convert-time-from-24-hour-to-12-hour-format` folder

</details>

### PR DESCRIPTION
**Pull request by Preetiraj3697**
Closes codinasion/codinasion#3187
Closes codinasion/codinasion#3208

### CODE REVIEW

**Review by anandfresh — DISMISSED** [review]
Please add the issue id's

**Comment by Preetiraj3697** [comment]
> Please add the issue id's

I already add id's
Write a F# program to convert days to hours codinasion/codinasion#3187
Write a F# program to convert time from 24-hour to 12-hour format codinasion/codinasion#3208

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Comment by Preetiraj3697** [comment]
Most Welcome @harshraj8843

**Pull request merged**
