### PR TITLE
Square of a number

### PR DESCRIPTION
**Pull request by harshi1122**
### Why:

Closes https://github.com/codinasion/codinasion/issues/89

### What's being changed:
- Added a Python program that outputs the square of a given number
### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hii @harshi1122 

Thanks for your continuous contributions 👍🏻

**Comment by harshi1122** [comment]
> Hii @harshi1122
> 
> Thanks for your continuous contributions 👍🏻

I am looking to contribute more here on Codinasion! 
I like this organization :)

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Please add a `README.md` for `python/programme/6-square-of-number/`

**Comment by harshi1122** [comment]
Hey @harshraj8843 

I have made necessary changes and pushed them to the branch here but I don't know why the changes aren't visible here.
They are somehow visible in the recent branch of XpowerY which I made

Is that a problem? 
If something doesn't work, please guide me.

**Comment by harshi1122** [comment]
Hey
I will work on it soon
I messed up the branches and will make changes tomorrow
Thanks

**Review by harshraj8843 — APPROVED** [review]

**Comment by harshraj8843** [comment]
` Preview ` : https://codinasion--pr10-dev-65w226w0.web.app/python/programme/6-square-of-number/

<sub>(expires Sun, 27 Feb 2022 02:52:38 GMT)</sub>

**Comment by harshraj8843** [comment]
` LIVE ` : https://codinasion.web.app/python/programme/6-square-of-number/

**Pull request merged**
