### PR TITLE
Volumeof cube

### LINKED ISSUE #9: Write a Java program to print hello world
### Description

Write a Java program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.java` file
- Add `PrintHelloWorld.java` file in `print-hello-world` folder

</details>

### LINKED ISSUE #10: Write a Java program to print hello world
### Description

Write a Java program to print hello world

### Desciption

```
Hello World !!!
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintHelloWorld.java` file
- Add `PrintHelloWorld.java` file in `print-hello-world` folder

</details>

### LINKED ISSUE #54: Write a Java program to find volume of cube
### Description

Write a Java program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.java` file
- Add `FindVolumeOfCube.java` file in `find-volume-of-cube` folder

</details>

### LINKED ISSUE #70: Write a Java program to find volume of cube
### Description

Write a Java program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfCube.java` file
- Add `FindVolumeOfCube.java` file in `find-volume-of-cube` folder

</details>

### LINKED ISSUE #75: Write a Java program to find volume of a cuboid
### Description

Write a Java program to find volume of a cuboid

Volume of a cuboid = `Length` × `Width` × `Height`

```
Length : 2
Width  : 3
Height : 4

Volume : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACuboid.java` file
- Add `FindVolumeOfACuboid.java` file in `find-volume-of-a-cuboid` folder

</details>

### LINKED ISSUE #92: Write a Java program to find volume of a cuboid
### Description

Write a Java program to find volume of a cuboid

Volume of a cuboid = `Length` × `Width` × `Height`

```
Length : 2
Width  : 3
Height : 4

Volume : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACuboid.java` file
- Add `FindVolumeOfACuboid.java` file in `find-volume-of-a-cuboid` folder

</details>

### PR DESCRIPTION
**Pull request by ashankritwik07**
### Why:

Closes codinasion/codinasion#10
Closes codinasion/codinasion#75 
Closes codinasion/codinasion#54

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @ashankritwik07 

Please update the linked issue for this and other PR(s) also

> Closes #ISSUE_NUMBER

For example `Closes codinasion/codinasion#2`

**Comment by ashankritwik07** [comment]
> 

Done sir , do check

**Review by SpirosArk — APPROVED** [review]

**Comment by victoriacheng15** [comment]
> > 
> 
> Done sir , do check

@ashankritwik07 

The one you linked is this PR. It needs to be linked to the issue

**Comment by ashankritwik07** [comment]
@victoriacheng15 hi sir , please review the code.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
