### PR TITLE
Create FindSecondLargestNumberInAnArray kotlin program#3568

### LINKED ISSUE #3568: Write a Kotlin program to find second largest number in an array
### Description

Write a Kotlin program to find second largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSecondLargestNumberInAnArray.kt` file
- Add `FindSecondLargestNumberInAnArray.kt` file in `find-second-largest-number-in-an-array` folder

</details>

### PR DESCRIPTION
**Pull request by mrajen27**
Create FindSecondLargestNumberInAnArray kotlin program#3556
Closes codinasion/codinasion#2624

### CODE REVIEW

**Comment by Tc2r1** [comment]
@mrajen27 I have a repo that is not excluded you may be able to contribute to:

shameless self plug: lol its not as fancy as this one but its honestly to help newer developers, lmk:

https://github.com/Tc2r1/DevInterview_Questions

**Comment by victoriacheng15** [comment]
@mrajen27 

Please link language-specific issue.  

Thank you!

**Comment by mrajen27** [comment]
updated the issue for kotlin

**Review by victoriacheng15 — APPROVED** [review]
Looks good!

Thank you for contributing!

**Pull request merged**
