### PR TITLE
[Closed] Hello world

### PR DESCRIPTION
**Pull request by ashankritwik07**
### Why:

Closes #319

### CODE REVIEW

**Comment by ashankritwik07** [comment]
@SpirosArk hi ,sir problem assign by you is done so , please review the code.

**Comment by ashankritwik07** [comment]
@victoriacheng15  hi ,sir problem assign by you is done so , please review the code.

**Comment by ashankritwik07** [comment]
@codinasion/program  hi ,sir problem assign by you is done so , please review the code.

**Comment by harshraj8843** [comment]
Hey @ashankritwik07 

This PR will be reviewed and merged shortly.

The website for this repo is also `In Progress`, that's why there is a delay in code review.

Thanks

**Comment by harshraj8843** [comment]
Hey @ashankritwik07 

Please link the related issue

> Closes #ISSUE_NUMBER

For example `Closes #1`

**Comment by ashankritwik07** [comment]
> Hey @ashankritwik07
> 
> Please link the related issue
> 
> > Closes #ISSUE_NUMBER
> 
> For example `Closes #1`

Done

**Review by SpirosArk — APPROVED** [review]

**Comment by ashankritwik07** [comment]
@victoriacheng15 hi sir ,please review the code

**Comment by harshraj8843** [comment]
Files of this PR is already commited in PR #323

**Pull request closed without merging**
