### PR TITLE
Dev4

### LINKED ISSUE #642: Write a C++ program to find factorial of a number by recursion
### Description

Write a C++ program to find factorial of a number by recursion

Factorial of a number is the product of all the numbers from 1 to that number. For example, factorial of 5 is 5\*4\*3\*2\*1 = 120.

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindFactorialOfANumberByRecursion.cpp` file
- Add `FindFactorialOfANumberByRecursion.cpp` file in `find-factorial-of-a-number-by-recursion` folder

</details>

### LINKED ISSUE #785: Write a C++ program to find factorial of a number by recursion
### Description

Write a C++ program to find factorial of a number by recursion

Factorial of a number is the product of all the numbers from 1 to that number. For example, factorial of 5 is 5\*4\*3\*2\*1 = 120.

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindFactorialOfANumberByRecursion.cpp` file
- Add `FindFactorialOfANumberByRecursion.cpp` file in `find-factorial-of-a-number-by-recursion` folder

</details>

### PR DESCRIPTION
**Pull request by SRR-CODER**
### Why:

Closes codinasion/codinasion#642 

### What's being changed:

Cpp code for finding factorial of a number via recursion

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@SRR-CODER, please link all issues for the programs that you did.

Thank you!

**Comment by SRR-CODER** [comment]
codinasion/program#834 codinasion/program#838 codinasion/codinasion#602 codinasion/codinasion#622 codinasion/codinasion#642  @victoriacheng15

**Comment by victoriacheng15** [comment]
> codinasion/program#834 codinasion/program#838 codinasion/codinasion#602 codinasion/codinasion#622 codinasion/codinasion#642 @victoriacheng15

Please link them in the first comment with `Closes` keyword. Like you have done with issue 785

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
