### PR TITLE
Added a Ruby program to convert Fahrenheit to Kelvin

### LINKED ISSUE #4261: Write a Swift program to convert feet to inches
### Description

Write a Swift program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToInches.swift` file
- Add `ConvertFeetToInches.swift` file in `program/convert-feet-to-inches` folder

</details>

### LINKED ISSUE #4427: Write a Ruby program to convert fahrenheit to kelvin
### Description

Write a Ruby program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFahrenheitToKelvin.rb` file
- Add `ConvertFahrenheitToKelvin.rb` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

### LINKED ISSUE #5615: Write a Swift program to convert feet to inches
### Description

Write a Swift program to convert feet to inches

1 foot = 12 inches

```
Input  : 5
Output : 60
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFeetToInches.swift` file
- Add `ConvertFeetToInches.swift` file in `program/convert-feet-to-inches` folder

</details>

### LINKED ISSUE #7379: Write a Ruby program to convert fahrenheit to kelvin
### Description

Write a Ruby program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertFahrenheitToKelvin.rb` file
- Add `ConvertFahrenheitToKelvin.rb` file in `program/convert-fahrenheit-to-kelvin` folder

</details>

### PR DESCRIPTION
**Pull request by champati-v**
Closes codinasion/codinasion#4427
Closes codinasion/codinasion#4261

## 📑 Description

Added a Ruby program to convert fahrenheit to Kelvin

### Summary
🌡️🔄🚀

Added a Ruby program to convert Fahrenheit to Kelvin. The program takes user input and uses the file `program/convert-fahrenheit-to-kelvin/ConvertFahrenheitToKelvin.rb` to perform the conversion and output.

> _`Fahrenheit` input_
> _Convert to `Kelvin` and print_
> _Winter is coming_

### Walkthrough
*  Implement the main functionality of the program ([link](https://github.com/codinasion/program/pull/7456/files?diff=unified&w=0#diff-9b6c7ce7be9db408e0c1b16d3db041e6cb7344f5d4ba57651722212fe1b3355bR1-R5))

### CODE REVIEW

**Review by anandfresh — DISMISSED** [review]
@champati-v can you please add the #issue id to this PR

**Comment by champati-v** [comment]
@anandfresh Issue ID - codinasion/codinasion#4427

> @champati-v can you please add the #issue id to this PR

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 🤗

**Comment by champati-v** [comment]
Thank you so much for the approval !! Looking forward to contribute more.

**Pull request merged**
