### PR TITLE
Created Python projects for  converting numbers into words in Indian number system

### LINKED ISSUE #1325: Write a Python program to print number to words in indian numbering system
### Description

Write a Python program to print number to words in indian numbering system

```
Input  : 123456789
Output : One Hundred Twenty Three Crore Forty Five Lakh Sixty Seven Thousand Eight Hundred Ninety
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print-number-to-words-in-indian-numbering-system.py` file
- Add `print-number-to-words-in-indian-numbering-system.py` file in `print-number-to-words-in-indian-numbering-system` folder

</details>

### PR DESCRIPTION
**Pull request by Vignesh-dev07**
### Why:
To help create a program to convert numbers to words
Linked to issue "Write a Python program to print number to words in Indian numbering
Closes codinasion/codinasion#1052 

### What's being changed:
Created a new program

### CODE REVIEW

**Comment by Vignesh-dev07** [comment]
Hey could you help me out with tagging my PR with Hacktoberfest?

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Python program for `convert hours to seconds` is closed. Please remove this file.

**Review by victoriacheng15 — DISMISSED** [review]
`print number to words in indian numbering system`:

I copied and pasted your code and I got a different answer .

image

**Comment by Vignesh-dev07** [comment]
Hey @victoriacheng15, I think the README.md file output is incorrect. Its supposed to have another 0 in the input to get that output.
for input : 123456789 output should be twelve crore thirty four lakh fifty six thousand seven hundred eighty nine 
In the README.md file input ends with 9 but output says ninety.

**Comment by victoriacheng15** [comment]
@Vignesh-dev07 Ah I see. I am not familiar with Indian number system.  I am letting Harsh knows about this.

@harshraj8843 Can you check on this?

**Comment by harshraj8843** [comment]
Hey @Vignesh-dev07 

Sorry for the late reply. This program is working fine.

There was some typo while creating the issue. Thanks for noticing this 👍🏻 

```bash
Enter number :123456789
Twelve Crore Thirty Four Lakh Fifty Six Thousand Seven Hundred Eighty Nine
```

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Comment by Vignesh-dev07** [comment]
Hey @harshraj8843 @victoriacheng15 could you help me out with an issue I am facing in github?
I keep receiving mails asking me to resolve some auto create issue in github and i have tried googling it but not able to find the solution. It'll be really helpful if you could help me resolve this as I don't know anyone else working on github

**Comment by harshraj8843** [comment]
Hey @Vignesh-dev07 

This was a mistake.

While creating the workflow to auto-create new issues, I forgot to check the repo in which the workflow is running.

https://github.com/codinasion/program/blob/f9d49d36ae61351512769715c572d8eb955deec7/.github/workflows/auto-create-issue.yml#L10

So, every fork was running this workflow with an error. That's why you were also receiving mail regarding the failure of this workflow run.

The workflow file has been updated this morning.

After updating your fork `master` branch, there will be no such workflow failures.

Sorry for any inconvenience caused.

**Comment by Vignesh-dev07** [comment]
Ohh I see yes I have updated my master branch in the evening and its no longer coming so thanks a lot.

**Pull request merged**
