### PR TITLE
ConvertMinutesToHours.js

### PR DESCRIPTION
**Pull request by samilieberman**
### Why:
Closes [#3511](https://github.com/codinasion/codinasion/issues/2580)

### What's being changed:
Add a JS function to convert minutes to hours

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@samilieberman 

The issue is assigned to someone else. Please look for other issues to contribute. Make sure you type !assign to grab the issue

Thank you!

**Comment by samilieberman** [comment]
Hi @victoriacheng15 , the PR that was raised for this issue is stale and was never merged: https://github.com/codinasion/program/pull/3641. Therefore, I put up a new PR to resolve this issue.

Thank you!
Sami

**Comment by victoriacheng15** [comment]
> Hi @victoriacheng15 , the PR that was raised for this issue is stale and was never merged: codinasion/program#3641. Therefore, I put up a new PR to resolve this issue.
> 
> Thank you! Sami

@samilieberman 

Yes, and thank you for letting me know. The issue is that you were not assigned to the issue and there may be a conflict with the bot or similar. But I can bring this to @harshraj8843 and see what he would like to do.

**Comment by harshraj8843** [comment]
Hey @samilieberman 

Sorry for this conflict, your solution is definitely better and it should be merged.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Comment by harshraj8843** [comment]
Hey @victoriacheng15 

Even if the previous PR is merged, this PR can be considered as the edit to the previous solution 👍🏻

**Pull request merged**
