### PR TITLE
C program to split a string into a character array

### LINKED ISSUE #2536: Write a C program to split string into array of characters
### Description

Write a C program to split string into array of characters

```
Input  : "hello world"
Output : ["h", "e", "l", "l", "o", " ", "w", "o", "r", "l", "d"]
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/SplitStringIntoArrayOfCharacters.c` file
- Add `SplitStringIntoArrayOfCharacters.c` file in `split-string-into-array-of-characters` folder

</details>

### PR DESCRIPTION
**Pull request by PravunathSingh**
### Why:
To add a C program to split a string into a character array 

Closes codinasion/codinasion#1875

### What's being changed:
New function is being added which takes in a string as an input and spilts it into a character array and then prints it.

### CODE REVIEW

**Review by victoriacheng15 — DISMISSED** [review]
Can you return the result in array format? Just like the issue mentioned.

Thank you!

**Comment by PravunathSingh** [comment]
> Can you return the result in array format? Just like the issue mentioned.
> 
> Thank you!

Sure, I'll do that

**Comment by PravunathSingh** [comment]
@victoriacheng15 I've made the changes, please review it.

**Comment by victoriacheng15** [comment]
@PravunathSingh 

Thank you! 👍 Also, can you remove the binary file?

**Comment by PravunathSingh** [comment]
@victoriacheng15 sorry for the delay, but I've removed the binary file. Please check it once.

**Comment by victoriacheng15** [comment]
@PravunathSingh 

You also added `.vscode` folder by accident. Please remove it as well. 

You may want to double-check what files you are current staged before push to branch. 

Thank you!

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
