### PR TITLE
Sum of num julia

### LINKED ISSUE #5347: Write a Julia program to find sum of n natural numbers using formula
### Description

Write a Julia program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-sum-of-n-natural-numbers-using-formula.jl` file
- Add `find-sum-of-n-natural-numbers-using-formula.jl` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

### LINKED ISSUE #5421: Write a Swift program to find sum of digits of a number
### Description

Write a Swift program to find sum of digits of a number

Suppose you have a number `n` and you want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

```
Input  : 123
Output : 6
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindSumOfDigitsOfANumber.swift` file
- Add `FindSumOfDigitsOfANumber.swift` file in `program/find-sum-of-digits-of-a-number` folder

</details>

### LINKED ISSUE #7481: Write a Julia program to find roots of quadratic equation
### Description

Write a Julia program to find roots of quadratic equation

Use the quadratic formula to find the roots of the quadratic equation

x = $\(-b &plusmn \sqrt\(b^2 - 4ac\)\)/2a$

The input will be the coefficients of $x^2$, $x$, and the constant $c$.

```
Input  : 1 2 1
Output : -1 -1
```

<sub>Contributed by - @PavanKumarCB</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `find-roots-of-quadratic-equation.jl` file
- Add `find-roots-of-quadratic-equation.jl` file in `program/find-roots-of-quadratic-equation` folder

</details>

### PR DESCRIPTION
**Pull request by champati-v**
## 📑 Description
Julia program to find the sum of n natural numbers using the formula (n*(n+1))/2
Julia program to find the roots of the quadratic equation
Swift program to find the sum of digits of a number

Closes codinasion/codinasion#3998
Closes codinasion/codinasion#4445 
Closes codinasion/codinasion#4071

---

### Summary
:heavy_plus_sign::1234::computer:

This pull request adds three programs in Julia and Swift to the `program` directory of the repository. The programs demonstrate how to find the roots of a quadratic equation, the sum of digits of a number, and the sum of first n natural numbers using different algorithms and functions.

> _`find_roots`, `SumOfN`_
> _Swift and Julia programs_
> _Autumn of learning_

### Walkthrough
*  Add three programs in different languages to find the roots of a quadratic equation, the sum of digits of a number, and the sum of first n natural numbers using a formula ([link](https://github.com/codinasion/program/pull/7534/files?diff=unified&w=0#diff-8b00f2017a36d62ec8720bd77158c8d4ef5e0ada5cbb981f680b920f6f918789R1-R32), [link](https://github.com/codinasion/program/pull/7534/files?diff=unified&w=0#diff-c514eca9383ad5980f38656abdfe0bd42d9c9d60bfeb5d625aec8f233ba07866L1-R20), [link](https://github.com/codinasion/program/pull/7534/files?diff=unified&w=0#diff-a7b1283585be1a429148a9838474795b48089b3058a5fe0383988ced021721e2L1-R6))

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@champati-v  please link all issues as shown below, thank you!

```
Closes #000
Closes codinasion/codinasion#2
Closes codinasion/codinasion#3
```

**Comment by champati-v** [comment]
@victoriacheng15 


> ## 📑 Description
> Julia program to find the sum of n natural numbers using the formula (n*(n+1))/2 Julia program to find the roots of the quadratic equation Swift program to find the sum of digits of a number
> 
> Closes #5347 Closes #7481 Closes #5421
> 
> ### 🤖 Generated by Copilot at [868df60](https://github.com/codinasion/program/commit/868df6028d28243fb880a429ff66ccb75002f63c)
> ### Summary
> ➕🔢💻
> 
> This pull request adds three programs in Julia and Swift to the `program` directory of the repository. The programs demonstrate how to find the roots of a quadratic equation, the sum of digits of a number, and the sum of first n natural numbers using different algorithms and functions.
> 
> > _`find_roots`, `SumOfN`_
> > _Swift and Julia programs_
> > _Autumn of learning_
> 
> ### Walkthrough
> * Add three programs in different languages to find the roots of a quadratic equation, the sum of digits of a number, and the sum of first n natural numbers using a formula ([link](https://github.com/codinasion/program/pull/7534/files?diff=unified&w=0#diff-8b00f2017a36d62ec8720bd77158c8d4ef5e0ada5cbb981f680b920f6f918789R1-R32), [link](https://github.com/codinasion/program/pull/7534/files?diff=unified&w=0#diff-c514eca9383ad5980f38656abdfe0bd42d9c9d60bfeb5d625aec8f233ba07866L1-R20), [link](https://github.com/codinasion/program/pull/7534/files?diff=unified&w=0#diff-a7b1283585be1a429148a9838474795b48089b3058a5fe0383988ced021721e2L1-R6))

**Comment by champati-v** [comment]
@victoriacheng15 
Apologies, 
Actually I accidentally closed this PR. I have reopened it and also linked all the issues in the above comment

> ## 📑 Description
> Julia program to find the sum of n natural numbers using the formula (n*(n+1))/2 Julia program to find the roots of the quadratic equation Swift program to find the sum of digits of a number
> 
> Closes codinasion/codinasion#3998 Closes codinasion/codinasion#4445 Closes codinasion/codinasion#4071
> 
> ### 🤖 Generated by Copilot at [868df60](https://github.com/codinasion/program/commit/868df6028d28243fb880a429ff66ccb75002f63c)
> ### Summary
> ➕🔢💻
> 
> This pull request adds three programs in Julia and Swift to the `program` directory of the repository. The programs demonstrate how to find the roots of a quadratic equation, the sum of digits of a number, and the sum of first n natural numbers using different algorithms and functions.
> 
> > _`find_roots`, `SumOfN`_
> > _Swift and Julia programs_
> > _Autumn of learning_
> 
> ### Walkthrough
> * Add three programs in different languages to find the roots of a quadratic equation, the sum of digits of a number, and the sum of first n natural numbers using a formula ([link](https://github.com/codinasion/program/pull/7534/files?diff=unified&w=0#diff-8b00f2017a36d62ec8720bd77158c8d4ef5e0ada5cbb981f680b920f6f918789R1-R32), [link](https://github.com/codinasion/program/pull/7534/files?diff=unified&w=0#diff-c514eca9383ad5980f38656abdfe0bd42d9c9d60bfeb5d625aec8f233ba07866L1-R20), [link](https://github.com/codinasion/program/pull/7534/files?diff=unified&w=0#diff-a7b1283585be1a429148a9838474795b48089b3058a5fe0383988ced021721e2L1-R6))

@victoriacheng15 
Apologies, 
Actually I accidentally closed this PR. I have reopened it and also linked all the issues in the above comment

**Review by victoriacheng15 — APPROVED** [review]
Thank you for contributing!

**Pull request merged**
