### PR TITLE
Added initial hover animations

### LINKED ISSUE #1: Add Pagination
Add pagination for [`https://codinasion.org/program`](https://codinasion.org/program)

### LINKED ISSUE #22: Add hover animations to Project components
I would like to add some hover animations to Project components (probably scale them with the transform property). It's a well-known and commonly used pattern to improve user experience.

### PR DESCRIPTION
**Pull request by Petrosdevri**
### Why:

Closes #22.

### What's being changed:
Add hover animations in Project components.

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @Petrosdevri 

It's working 🎉 

But the scaling is high (I think 🤔)

**Comment by Petrosdevri** [comment]
Yeah I just found it out. I think there was a problem with my browser (I used Firefox at this case and it didn't render them properly). I will fix scaling immediately.

**Comment by Petrosdevri** [comment]
I am currently on my phone so I don't have the ability to look at the values. I will be back in 2-3 hours so you will be able to update the request later.

**Review by harshraj8843 — APPROVED** [review]
It's really cool 😍

**Pull request merged**
