### PR TITLE
Add Area of Circle Python Function

### LINKED ISSUE #233: Area of Circle
### Title of article

Write a Python programme to find the area of circle.

### Additional information

r : radius of circle
pi : 3.141

### Programme

```
Enter r : 3

Area : 28.27
```

### Formula

```
Area of circle = pi * (r^2)
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by theanorak**
### Why:

Closes #233 

### What's being changed:

Added a python program that prints area of a circle based on radius input from user.

### Check off the following:

- [ x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hii @theanorak 

Thanks for contributing to this open source project 😃 

This PR will be reviewed and merged shortly

**Comment by harshraj8843** [comment]
` Preview ` : https://codinasion--pr18-dev-5o7hj3iz.web.app/programme/area-of-circle/

**Comment by theanorak** [comment]
> Hii @theanorak 
> 
> Thanks for contributing to this open source project 😃 
> 
> This PR will be reviewed and merged shortly

Thanks as well for the opportunity! This has been one of my first PRs as I'm in the process of learning. Looking forward to working on the other issues ☺️

**Comment by harshraj8843** [comment]
` LIVE ` : https://codinasion.web.app/programme/area-of-circle/

**Pull request merged**
