### PR TITLE
[Closed] Added C program for converting string to integer

### PR DESCRIPTION
**Pull request by HeYPoonam**
Why: resolve issues - Hacktoberfest2022

Closes [#2482](https://github.com/codinasion/codinasion/issues/1829)

What's being changed: 
Write a solution c program for converting string to integer

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@HeYPoonam 

Please link language-specific issue. 

Thank you!

**Comment by HeYPoonam** [comment]
@victoriacheng15 
What is language-specific issue?

**Comment by HeYPoonam** [comment]
Why:
resolve issues - Hacktoberfest2022

Closes https://github.com/codinasion/codinasion/issues/1829

What's being changed:
Write a solution c program for converting string to integer

**Comment by victoriacheng15** [comment]
> Why: resolve issues - Hacktoberfest2022
> 
> Closes codinasion/codinasion#1829
> 
> What's being changed: Write a solution c program for converting string to integer

Please edit the first comment with the info you just provided.

**Comment by victoriacheng15** [comment]
@HeYPoonam 

As I mentioned in other PRs, this issue was assigned to someone else. Please look for other issues to contribute. And make sure you type `!assign` to grab the issue.

Thank you!

**Pull request closed without merging**
