### PR TITLE
Code to print reverse of a number using GoLang

### LINKED ISSUE #3474: Write a GO program to print reverse of a number
### Description

Write a GO program to print reverse of a number

Reverse of a number is the number obtained by reversing the digits of the original number. For example, the reverse of 123 is 321. The reverse of 100 is 1. The reverse of 1000 is 1.

```
Input  : 123
Output : 321
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/print_reverse_of_a_number.go` file
- Add `print_reverse_of_a_number.go` file in `print-reverse-of-a-number` folder

</details>

### PR DESCRIPTION
**Pull request by devkansara**
### Why:

Closes codinasion/codinasion#2556

### What's being changed:
Added code to print reverse of a number using GoLang

### CODE REVIEW

**Review by MadhuS-1605 — CHANGES_REQUESTED** [review]
for the input value: 99009900
getting output like this: Enter any Number to find its Reverse = 990099
expected output: 00990099

**Comment by devkansara** [comment]
Updated the code, please check and revert

**Comment by devkansara** [comment]
Hey, can this pull request get reviewed

**Comment by MadhuS-1605** [comment]
> Hey, can this pull request get reviewed

sure will check

**Review by MadhuS-1605 — APPROVED** [review]
LGTM! Thanks for contributing @devkansara

**Pull request merged**
