### PR TITLE
Hexadecimal to binary conversion in java

### LINKED ISSUE #635: Write a Java program to convert hexadecimal to binary
### Description

Write a Java program to convert hexadecimal to binary

Hexadecimal is a base-16 number system. It uses sixteen digits: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, and F. The digits are called hexits. A hexit is the smallest unit of information in a computer. A hexit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, or F, or it can be used to represent a single state, such as on or off.

Binary is a base-2 number system. It uses only two digits: 0 and 1. The digits are called bits. A bit is the smallest unit of information in a computer. A bit can be either 0 or 1. A bit can be used to represent a single value, such as 0 or 1, or it can be used to represent a single state, such as on or off.

To convert a hexadecimal number to binary, we can use the following algorithm:

1. Convert the hexadecimal number to decimal.
2. Convert the decimal number to binary.

```
Input  : A
Output : 1010
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertHexadecimalToBinary.java` file
- Add `ConvertHexadecimalToBinary.java` file in `convert-hexadecimal-to-binary` folder

</details>

### PR DESCRIPTION
**Pull request by imtiyaz786**
Program for Hexadecimal to binary conversion added.

### Why:

Closes codinasion/codinasion#525

### CODE REVIEW

**Comment by imtiyaz786** [comment]
#635

**Review by victoriacheng15 — COMMENTED** [review]
Tried to run the function with a couple of online editors and got the same error.

image

**Comment by imtiyaz786** [comment]
> Tried to run the function with a couple of online editors and got the same error.
> 
> image

Hi, I used notepad++ to write the code and command prompt to compile and run the code. It works completely find.

image

**Comment by imtiyaz786** [comment]
It could be due to absence of .class file. Could you please try this by creating your own custom class. Thanks

**Comment by imtiyaz786** [comment]
> Tried to run the function with a couple of online editors and got the same error.
> 
> image

I just checked. This error occurs when we keep class name and file name different.

**Comment by victoriacheng15** [comment]
> > Tried to run the function with a couple of online editors and got the same error.
> > image
> 
> I just checked. This error occurs when we keep class name and file name different.

Ah, I see! I just followed what you suggested. It works. 

Thank you for the tip! 👍

**Review by victoriacheng15 — APPROVED** [review]
Thank you for contributing!

**Pull request merged**
