### PR TITLE
feat: add main.py

### LINKED ISSUE #615: Write a Python program to convert octal to decimal
### Description

Write a Python program to convert octal to decimal

Octal is a base-8 number system. It uses only eight digits: 0, 1, 2, 3, 4, 5, 6, and 7. The digits are called octits. An octit is the smallest unit of information in a computer. An octit can be used to represent a single value, such as 0, 1, 2, 3, 4, 5, 6, or 7, or it can be used to represent a single state, such as on or off.

To convert an octal number to decimal, we can use the following algorithm:

1. Multiply the first octit by 8^0.
2. Multiply the second octit by 8^1.
3. Multiply the third octit by 8^2.
4. Multiply the fourth octit by 8^3.
5. Repeat steps 3 and 4 until the last octit.
6. Add the results of all the multiplications.
7. The decimal number is the sum of all the multiplications.

```
Input  : 12
Output : 10
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert-octal-to-decimal.py` file
- Add `convert-octal-to-decimal.py` file in `convert-octal-to-decimal` folder

</details>

### PR DESCRIPTION
**Pull request by galahad42**
### Why:

Closes codinasion/codinasion#511 

### What's being changed:
Add main.py file which converts octal to decimal

### CODE REVIEW

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
- Please move `convert-binary-to-octal` folder inside `program` folder

- Please follow `file naming convension`. For more info about it please see `How to contribute` dropdown on the related issue

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Please move `convert-binary-to-octal` folder inside `program` folder

**Review by victoriacheng15 — APPROVED** [review]
Thank you for updating file name and contributing!

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
