### PR TITLE
Added ConvertAStringToAnInteger(withoutUsingBuilt-inFunctions).ts

### LINKED ISSUE #2501: Write a TypeScript program to convert a string to an integer (without using built-in functions)
### Description

Write a TypeScript program to convert a string to an integer (without using built-in functions)

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertAStringToAnInteger(withoutUsingBuilt-inFunctions).ts` file
- Add `ConvertAStringToAnInteger(withoutUsingBuilt-inFunctions).ts` file in `convert-a-string-to-an-integer-(without-using-built-in-functions)` folder

</details>

### PR DESCRIPTION
**Pull request by ahmedheltaher**
### Why:

Closes codinasion/codinasion#1848

### What's being changed:
Added ''ConvertAStringToAnInteger(withoutUsingBuilt-inFunctions).ts'

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@ahmedheltaher 

Please type `!assign` in the TS issue. 

I removed python issue since it was assigned to someone else.

Thank you!

**Comment by ahmedheltaher** [comment]
Yah, that alright.
I typed `!assign`

Thank you

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Looks good! And please remove python file.

Thank you for contributing!

**Comment by ahmedheltaher** [comment]
Ok i will do it. In just a few minutes

**Comment by victoriacheng15** [comment]
> Ok i will do it. In just a few minutes

Thank you!!! 👍

**Review by victoriacheng15 — APPROVED** [review]

**Pull request merged**
