### PR TITLE
Created LinearSearch.ts

### LINKED ISSUE #1638: Write a TypeScript program for linear search
### Description

Write a TypeScript program for linear search

Linear search is a very simple search algorithm. In this type of search, a sequential search is made over all items one by one. Every item is checked and if a match is found then that particular item is returned, otherwise the search continues till the end of the data collection.

```
Input  : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Target : 5

Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `LinearSearch.ts` file
- Add `LinearSearch.ts` file in `dsa/linear-search` folder

</details>

### LINKED ISSUE #2199: Linear Search
### Description

Write a program for linear search

Linear search is a very simple search algorithm. In this type of search, a sequential search is made over all items one by one. Every item is checked and if a match is found then that particular item is returned, otherwise the search continues till the end of the data collection.

```
Input  : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Target : 5

Output : 4
```

### Tracking Issues

- [x] #2200
- [x] #2201
- [x] #2202
- [x] #2203
- [x] #2204
- [x] #2205
- [x] #2206
- [x] #2207
- [x] #2208
- [x] #2209
- [x] #2210
- [x] #2211
- [x] #2212
- [x] #2213
- [x] #2214
- [x] #2215
- [x] #2216
- [x] #2217
- [x] #2218
- [x] #2219

### LINKED ISSUE #2219: Write a TypeScript program for linear search
### Description

Write a TypeScript program for linear search

Linear search is a very simple search algorithm. In this type of search, a sequential search is made over all items one by one. Every item is checked and if a match is found then that particular item is returned, otherwise the search continues till the end of the data collection.

```
Input  : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Target : 5

Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `LinearSearch.ts` file
- Add `LinearSearch.ts` file in `dsa/linear-search` folder

</details>

### PR DESCRIPTION
**Pull request by vedha-vikash-pixel**
Wrote a TypeScript program to linear search a array.

### Why:
Closes codinasion/codinasion#1638 

### What's being changed:
TypeScript Linear Search program

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @vedha-vikash-pixel 

Please use language specific issue `Closes codinasion/codinasion#1638`

**Comment by vedha-vikash-pixel** [comment]
> Hey @vedha-vikash-pixel
> 
> Please use language specific issue `Closes codinasion/codinasion#1638`

Sorry , But I don't get what you are trying to say.

**Comment by harshraj8843** [comment]
> Wrote a TypeScript program to linear search a array.
>
> Why:
> Closes codinasion/codinasion#1618
>
> What's being changed:
> TypeScript Linear Search program

In the description, you linked issue `2199`, but the language specific issue is `2219`

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
