### PR TITLE
Added C Code for checking Prime number

### LINKED ISSUE #29: Check prime number
### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### Title of article

Write a c program to check prime number.

### Additional information

```
Input  : 8
Output : Not prime number
```

```
Input  : 7
Output : Prime number
```

### PR DESCRIPTION
**Pull request by NeelPatel31**
### Why:

Closes #29

### What's being changed:

Added C Code for checking Prime number

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @NeelPatel31 

Thanks for your contributions to this project

But, the folder [`check-prime-number`](https://github.com/NeelPatel31/codinasion/tree/master/programme/check-prime-number) is already created. Please apply changes in that folder, no need to create additional folder.

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Please consider these :- 

- [ ] add `solution.c` in [`check-prime-number`](https://github.com/NeelPatel31/codinasion/tree/master/programme/check-prime-number) folder
- [ ] update [`index.md`](https://github.com/NeelPatel31/codinasion/blob/master/programme/check-prime-number/index.md)
- [ ] update [`README.md`](https://github.com/NeelPatel31/codinasion/blob/master/programme/check-prime-number/README.md)
- [ ] delete [`Check-Prime-Number`](https://github.com/NeelPatel31/codinasion/tree/master/programme/Check-Prime-Number) folder

**Comment by NeelPatel31** [comment]
* [x]  add `solution.c` in [`check-prime-number`](https://github.com/NeelPatel31/codinasion/tree/master/programme/check-prime-number) folder
 * [x]  update [`index.md`](https://github.com/NeelPatel31/codinasion/blob/master/programme/check-prime-number/index.md)
 * [x]  update [`README.md`](https://github.com/NeelPatel31/codinasion/blob/master/programme/check-prime-number/README.md)
 * [x]  delete [`Check-Prime-Number`](https://github.com/NeelPatel31/codinasion/tree/master/programme/Check-Prime-Number) folder

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by harshraj8843** [comment]
` Preview ` : https://codinasion--pr30-dev-6lg83kx6.web.app/programme/check-prime-number/

<sub>(expires Fri, 11 Mar 2022 11:33:22 GMT)</sub>

**Comment by harshraj8843** [comment]
` LIVE ` : https://codinasion.web.app/programme/check-prime-number/

**Pull request merged**
