### PR TITLE
Ready for review

### LINKED ISSUE #2291: Write a Python program to convert miles to inches
### Description

Write a Python program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-miles-to-inches.py` file
- Add `convert-miles-to-inches.py` file in `convert-miles-to-inches` folder

</details>

### LINKED ISSUE #3090: Convert miles to inches
### Description

Write a program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```

### Tracking Issues

- [ ] Write a C program to convert miles to inches
- [ ] Write a C# program to convert miles to inches
- [ ] Write a C++ program to convert miles to inches
- [ ] Write a Dart program to convert miles to inches
- [ ] Write a F# program to convert miles to inches
- [ ] Write a GO program to convert miles to inches
- [ ] Write a Haskell program to convert miles to inches
- [ ] Write a Java program to convert miles to inches
- [ ] Write a JavaScript program to convert miles to inches
- [ ] Write a Julia program to convert miles to inches
- [ ] Write a Kotlin program to convert miles to inches
- [ ] Write a Perl program to convert miles to inches
- [ ] Write a PHP program to convert miles to inches
- [ ] Write a Python program to convert miles to inches
- [ ] Write a R program to convert miles to inches
- [ ] Write a Ruby program to convert miles to inches
- [ ] Write a Rust program to convert miles to inches
- [ ] Write a Scala program to convert miles to inches
- [ ] Write a Swift program to convert miles to inches
- [ ] Write a TypeScript program to convert miles to inches

### LINKED ISSUE #3104: Write a Python program to convert miles to inches
### Description

Write a Python program to convert miles to inches

1 mile = 63360 inches

```
Input  : 5
Output : 316800
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-miles-to-inches.py` file
- Add `convert-miles-to-inches.py` file in `convert-miles-to-inches` folder

</details>

### PR DESCRIPTION
**Pull request by sushmita2109**
### Why:

Closes codinasion/codinasion#2291

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@sushmita2109 

Please link language-specific issue.

Thank you!

**Comment by sushmita2109** [comment]
Issue: Write a Python program to convert centimeters to inches .

It's a python language code

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Hey @sushmita2109 

Please move program file to `program/convert-miles-to-inches.py` folder

**Comment by sushmita2109** [comment]
done

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
File is still in `program/calculate-compound-interest/` folder

last commit just created a new same file

**Comment by victoriacheng15** [comment]
@sushmita2109 

Please remove `calculate-miles-to-inches.py` file in `calculate-compound-interest` folder

**Comment by sushmita2109** [comment]
deleted

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
