### PR TITLE
Created unassign_users.py

### LINKED ISSUE #5709: Unassign Issues
Write a script to unassign users from `good first issue` whose assignment is older than a month.

### Why

Hundreds of `good first issue` were assigned to different contributors during `Hacktoberfest 2022` but were never completed.

### How to contribute

- Add a python script inside the `scripts` folder
- create a PR

---

The way I am thinking of the solution is as follows:- 

1. `GET` all `good-first-issues` from the Github API

	`GET` https://api.github.com/repos/codinasion/program/issues?labels=good%20first%20issue

3. Check for the length of `assignees`. If length > 0

5. `Get` issue events from the Github API

	`GET` https://api.github.com/repos/codinasion/program/issues/5657/events

7. Find the latest assignment event

	```json
	"event": "assigned",
	```

9. Check event time and compare from time. now

	```json
	"created_at": "2022-12-31T14:57:00Z",
	```

11. If the assignment is older than a specific time period unassign the user

	https://docs.github.com/en/rest/issues/assignees?apiVersion=2022-11-28#remove-assignees-from-an-issue

### PR DESCRIPTION
**Pull request by patel-aum**
### Why:

Closes codinasion/codinasion#4306

### CODE REVIEW

**Comment by brundabharadwaj** [comment]
Hi @patel-aum , May I know the steps to test this functionality?

**Comment by patel-aum** [comment]
> 

just add your GITHUB token key and change repo_owner,repo_name field

**Comment by harshraj8843** [comment]
The script has been tested successfully 🥳 

Tested 👉🏻 codinasion/codinasion#3062

But, this PR will be merged after some 🕐 

`Reason`: There are some issue which has been assigned prior, but the PRs to close those issues are waiting to be reviewed 👀 

So, first, we will review and merge all the available PRs

**Comment by patel-aum** [comment]
> The script has been tested successfully 🥳
> 
> Tested 👉🏻 codinasion/codinasion#3062
> 
> But, this PR will be merged after some 🕐
> 
> `Reason`: There are some issue which has been assigned prior, but the PRs to close those issues are waiting to be reviewed 👀
> 
> So, first, we will review and merge all the available PRs

okayy

**Review by harshraj8843 — APPROVED** [review]
Let's drop our `Little Boy` 💣 😅

**Pull request merged**
