### PR TITLE
feat(average of numbers by recursion in kotlin) : issue #4622

### LINKED ISSUE #4622: Write a Kotlin program to find average of numbers by recursion
### Description

Write a Kotlin program to find average of numbers by recursion

Average of numbers is the sum of all numbers divided by the number of numbers. For example, the average of 1, 2, 3, 4, 5 is 3. The average of 1, 2, 3, 4, 5, 6 is 3.5.

Average of numbers can be calculated by recursion. The average of numbers is the sum of the first number and the average of the rest of the numbers. The average of the rest of the numbers is the sum of the second number and the average of the rest of the numbers. The average of the rest of the numbers is the sum of the third number and the average of the rest of the numbers. And so on.

```
Input  : 1 2 3 4 5
Output : 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindAverageOfNumbersByRecursion.kt` file
- Add `FindAverageOfNumbersByRecursion.kt` file in `find-average-of-numbers-by-recursion` folder

</details>

### PR DESCRIPTION
**Pull request by mrajesh09**
### Why:

Closes codinasion/codinasion#3507

### What's being changed:
Added a Program for finding average of numbers by recursion in kotlin

### CODE REVIEW

**Comment by victoriacheng15** [comment]
@mrajesh09 

Please type `!assign` in the issue.

Thank you!

**Comment by mrajesh09** [comment]
> @mrajesh09
> 
> Please type `!assign` in the issue.
> 
> Thank you!

Done! Thanks you!

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
It doesnt run for me. 

image

**Comment by mrajesh09** [comment]
> It doesnt run for me.
> 
> image

Fixed the issue, please review now! Thanks

**Review by victoriacheng15 — APPROVED** [review]

**Pull request merged**
